In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
import os
import pandas as pd

GTFS_CLEAN = "/content/drive/MyDrive/GTFS_CLEAN"   # adapte si besoin

all_agencies = []  # liste pour stocker tous les df

# Parcourir les sous-dossiers
for subfolder in sorted(os.listdir(GTFS_CLEAN)):
    folder_path = os.path.join(GTFS_CLEAN, subfolder)

    # vérifier que c'est un dossier
    if not os.path.isdir(folder_path):
        continue

    agency_path = os.path.join(folder_path, "agency.txt")

    # vérifier que le fichier existe
    if os.path.exists(agency_path):
        try:
            df = pd.read_csv(agency_path, encoding="utf-8", on_bad_lines="skip")
            df["source_folder"] = subfolder  # pour savoir d'où vient le fichier
            all_agencies.append(df)
            print(f"📥 agency.txt chargé depuis : {subfolder}")
        except Exception as e:
            print(f"⚠️ Erreur lecture dans {subfolder}: {e}")
    else:
        print(f"❌ Aucun agency.txt dans : {subfolder}")

📥 agency.txt chargé depuis : AISA (Bus Madrid-Aranda de Duero-Burgo de Osma)
📥 agency.txt chargé depuis : ALSA buses
📥 agency.txt chargé depuis : AUCORSA (Autobuses de Córdoba S.A.)
📥 agency.txt chargé depuis : AUTNA SL
📥 agency.txt chargé depuis : Alavabus
📥 agency.txt chargé depuis : Alvarez Travelers Coaches
📥 agency.txt chargé depuis : Ancebus
📥 agency.txt chargé depuis : Auif Irunbus (Lurraldebus)
📥 agency.txt chargé depuis : Autocares Baraza (Baraza Coaches)
📥 agency.txt chargé depuis : Autocares Rías Baixas (Rías Baixas Coaches)
📥 agency.txt chargé depuis : Autocorb Coaches
📥 agency.txt chargé depuis : Autoridad de Transporte Metropolitano del Area de Barcelona (ATM) Buses and trains in Catalonia (full version)
📥 agency.txt chargé depuis : Avanza Grupo (Ávila city bus)
📥 agency.txt chargé depuis : Avanza Grupo (Huesca city bus)
📥 agency.txt chargé depuis : Avanza Grupo (Mataró city bus)
📥 agency.txt chargé depuis : Avanza Grupo (Segovia city bus)
📥 agency.txt chargé depuis : Avanza Grupo (Soria city bus)
📥 agency.txt chargé depuis : Avanza Grupo (VAC-124. Huesca-Lleida with branches)
📥 agency.txt chargé depuis : Avanza Grupo (VAC-245. Huesca-Barcelona)
📥 agency.txt chargé depuis : Àrea Metropolitana de Barcelona (AMB)
📥 agency.txt chargé depuis : Bermibusa
📥 agency.txt chargé depuis : Bizkaibus
📥 agency.txt chargé depuis : BlaBlaCar Bus
📥 agency.txt chargé depuis : Catalonia Area de Barcelona
📥 agency.txt chargé depuis : City Council of Las Palmas de Gran Canaria (city bus)
📥 agency.txt chargé depuis : Collegamenti marittimi Grandi Navi Veloci
📥 agency.txt chargé depuis : Collegamenti marittimi Grimaldi
📥 agency.txt chargé depuis : Consorcio Regional de Transportes de Madrid CRTM Intercity Buses (Madrid Intercity Bus)
📥 agency.txt chargé depuis : Consorcio Regional de Transportes de Madrid CRTM Light Rail Network (Red de Metro Ligero)
📥 agency.txt chargé depuis : Consorcio Regional de Transportes de Madrid CRTM Madrid City Bus (Autobus urbano de Madrid)
📥 agency.txt chargé depuis : Consorcio Regional de Transportes de Madrid Métro Ligero de Madrid
📥 agency.txt chargé depuis : Consorcio Regional de Transportes de Madrid Réseau de navettes CRTM (Red de Cercanías)
📥 agency.txt chargé depuis : Costa Coaches
📥 agency.txt chargé depuis : Cots Alsina
📥 agency.txt chargé depuis : Direxis Masats
📥 agency.txt chargé depuis : Direxis TGO (Transportes Generales de Olesa)
📥 agency.txt chargé depuis : EMT Tarragona
📥 agency.txt chargé depuis : El Transbordador de Vizcaya
📥 agency.txt chargé depuis : El Transbordador de Vizcaya (Bizkaia Bridge Ferry)
📥 agency.txt chargé depuis : Empresa Municipal de Transportes de Madrid (EMT Madrid)
📥 agency.txt chargé depuis : Empresa Municipal de Transportes de Valencia (EMT Valencia)
📥 agency.txt chargé depuis : Empresa Municipal de Transports Urbans de Palma de Mallorca
📥 agency.txt chargé depuis : Erandio City Council (Erandio! Busa)
📥 agency.txt chargé depuis : Etxebarri Town Hall
📥 agency.txt chargé depuis : Euskotren
📥 agency.txt chargé depuis : FGV - Generalitat Valenciana Metro de Valencia
📥 agency.txt chargé depuis : FGV - Generalitat Valenciana Trains and trams in Alicante and the Costa Blanca
📥 agency.txt chargé depuis : Ferry Fred. Olsen (Fred Olsen Express)
📥 agency.txt chargé depuis : Funiculaire de Artxanda
📥 agency.txt chargé depuis : Generalitat of Catalonia (Intercity bus)
📥 agency.txt chargé depuis : Gobierno de Cantabria (Bus en Cantabrie)
📥 agency.txt chargé depuis : Granada City Council (Granada city bus)
📥 agency.txt chargé depuis : Guaguas Municipales
📥 agency.txt chargé depuis : Junta de Extremadura (Bus du gouvernement régional d’Estrémadure)
📥 agency.txt chargé depuis : Kbus (Barakaldo urban)
📥 agency.txt chargé depuis : La Burundesa_SA
📥 agency.txt chargé depuis : La Coruña Tram Company SA
📥 agency.txt chargé depuis : La Regional Vallisoletana SA
📥 agency.txt chargé depuis : La Veloz SA (Buses from the Belchite countryside area to Zaragoza (C12))
📥 agency.txt chargé depuis : Lázara Coaches
📥 agency.txt chargé depuis : Leioa City Council (Lejoan Busa)
📥 agency.txt chargé depuis : Lurraldebus - Hernani Urban (bus urbain d’Hernani)
📥 agency.txt chargé depuis : Lurraldebus Arrasate
📥 agency.txt chargé depuis : Lurraldebus Eibar
📥 agency.txt chargé depuis : Lurraldebus Ekialdebus
📥 agency.txt chargé depuis : Lurraldebus Euskotren bus
📥 agency.txt chargé depuis : Lurraldebus Goierrialdea
📥 agency.txt chargé depuis : Lurraldebus Guipuzcoana (La Guipuzcoana)
📥 agency.txt chargé depuis : Lurraldebus Lasarte
📥 agency.txt chargé depuis : Lurraldebus Oiartzun (Xorrola)
📥 agency.txt chargé depuis : Lurraldebus Pesa
📥 agency.txt chargé depuis : Lurraldebus TBH (Interurban Tolosa Buruntzaldea)
📥 agency.txt chargé depuis : Lurraldebus Tolosaldea
📥 agency.txt chargé depuis : Lurraldebus Urbano de Errentería (Errenteria Urbanoa)
📥 agency.txt chargé depuis : Lurraldebus Zarautz
📥 agency.txt chargé depuis : Metro de Sevilla
📥 agency.txt chargé depuis : MetroValencia
📥 agency.txt chargé depuis : Metropolitano de Tenerife (Metrotenerife)
📥 agency.txt chargé depuis : Métro Bilbao
📥 agency.txt chargé depuis : Métro de Madrid
📥 agency.txt chargé depuis : NVBW - Nahverkehrsgesellschaft Baden-Württemberg mbH
📥 agency.txt chargé depuis : Nouvelle-Aquitaine Mobilités
📥 agency.txt chargé depuis : Oñati urbain (Oñatiko herribusa)
📥 agency.txt chargé depuis : Ouigo
📥 agency.txt chargé depuis : Palma City Council (Palma de Mallorca city bus)
📥 agency.txt chargé depuis : Pinto City Council
📥 agency.txt chargé depuis : Rafael Nadal Coaches
📥 agency.txt chargé depuis : Réseau interurbain liO Occitanie
📥 agency.txt chargé depuis : Rodil
📥 agency.txt chargé depuis : Sopela Town Hall
📥 agency.txt chargé depuis : TIB Transports de les Illes Balears - CTM Transport Consortium of Mallorcam (Public transport on the island of Mallorca)
📥 agency.txt chargé depuis : TIB Transports of the Balearic Islands - CIE Consell Insular d'Eivissa (Ibiza Island Bus)
📥 agency.txt chargé depuis : TIB Transports of the Balearic Islands - CIME Consell Insular de Menorca (Menorca Island Bus)
📥 agency.txt chargé depuis : TMESA
📥 agency.txt chargé depuis : TRAM Alicante
📥 agency.txt chargé depuis : TUS (Transportes Urbanos de Santander)
📥 agency.txt chargé depuis : TUSSAM (Seville bus and tram)
📥 agency.txt chargé depuis : Tolosa City Council (Urbano de Tolosa)
📥 agency.txt chargé depuis : TranspRober
📥 agency.txt chargé depuis : Transports Municipals del Gironés SAU (TMG) Girona city bus
📥 agency.txt chargé depuis : Transports Municipaux D’Egara (TMESA) Terrassa bus urbain
📥 agency.txt chargé depuis : Vectalia Movilidad (bus de la ville de Cáceres)
📥 agency.txt chargé depuis : Viagón Coaches
📥 agency.txt chargé depuis : Xunta de Galicia Buses
📥 agency.txt chargé depuis : dBus (Donostiabus)

In [4]:
if all_agencies:
    agencies_df = pd.concat(all_agencies, ignore_index=True)
    print("\n📊 Total lignes agence :", len(agencies_df))
else:
    print("❌ Aucun fichier agency.txt trouvé.")

📊 Total lignes agence : 2372

In [6]:
# Afficher les 10 premières lignes
agencies_df.head(10)

,agency_id,agency_name,agency_url,agency_timezone,agency_lang,agency_phone,source_folder,agency_fare_url,agency_email,agency_branding_url
0,a-28005890,AISA,https://www.aisa-grupo.com/,Europe/Madrid,es,34918752018,AISA (Bus Madrid-Aranda de Duero-Burgo de Osma),NaN,NaN,NaN
1,300,ALSA,http://www.alsa.es,Europe/Madrid,es,902422242,ALSA buses,NaN,NaN,NaN
2,Aucorsa,Autobuses de Córdoba - S.A.,https://www.aucorsa.es,Europe/Madrid,es,957764676,AUCORSA (Autobuses de Córdoba S.A.),https://www.aucorsa.es/gestion_y_recarga_onlin...,NaN,NaN
3,autna,AUTNA,https://www.autna.com/,Europe/Madrid,es,0034 986 288 030,AUTNA SL,NaN,NaN,NaN
4,1,Álavabus,https://alavabus.eus/es,Europe/Madrid,es,945182060,Alavabus,https://alavabus.eus/es/tarifas-y-otros,alavabus@araba.eus,NaN
5,2,Transporte Comarcal,https://alavabus.eus/es,Europe/Madrid,es,945182060,Alavabus,https://alavabus.eus/es/tarifas-y-otros,alavabus@araba.eus,NaN
6,AUTOS ALVAREZ,AUTOS ALVAREZ DE VIAJEROS SL,http://vulpeti.com/moderniza/B49122856.zip,Europe/Madrid,es,980 62 05 01,Alvarez Travelers Coaches,NaN,NaN,NaN
7,ANCEBUS,"ANCEBUS, SL",http://www.ancebus.com/,Europe/Madrid,es,"923 480 575, 695 345 243",Ancebus,NaN,NaN,NaN
8,13,Auif,http://www.auif.es/,Europe/Madrid,es,943633111,Auif Irunbus (Lurraldebus),https://www.mugi.eus/index.php/es/tarjetas/tar...,NaN,NaN
9,1,Autocares Baraza,http://www.autocaresbaraza.com,Europe/Madrid,es,950390311,Autocares Baraza (Baraza Coaches),NaN,NaN,NaN

In [7]:
required_cols = ["agency_id", "agency_name", "agency_timezone"]

# Compter les valeurs null ou NaN
agencies_df[required_cols].isna().sum()

agency_id          1
agency_name        0
agency_timezone    0
dtype: int64

In [9]:
for col in required_cols:
    nan_count = agencies_df[col].isna().sum()
    empty_count = (agencies_df[col].astype(str).str.strip() == "").sum()

    print(f"🔹 {col} : NaN = {nan_count}, vides = {empty_count}, TOTAL = {nan_count + empty_count}")

🔹 agency_id : NaN = 1, vides = 0, TOTAL = 1
🔹 agency_name : NaN = 0, vides = 0, TOTAL = 0
🔹 agency_timezone : NaN = 0, vides = 0, TOTAL = 0

In [10]:
# Colonnes obligatoires
required_cols = ["agency_id", "agency_name", "agency_timezone"]

# Supprimer les lignes invalides
clean_df = agencies_df.dropna(subset=required_cols)

# Supprimer aussi les lignes vides ""
for col in required_cols:
    clean_df = clean_df[clean_df[col].astype(str).str.strip() != ""]

In [11]:
deleted_rows = len(agencies_df) - len(clean_df)
print(f"🚮 Lignes supprimées : {deleted_rows}")
print(f"📊 Lignes restantes : {len(clean_df)}")

🚮 Lignes supprimées : 1
📊 Lignes restantes : 2371

In [12]:
extra_cols = [
    "agency_url",
    "agency_lang",
    "agency_phone",
    "agency_fare_url",
    "agency_email",
    "agency_branding_url",
    "source_folder"
]

print("📊 Vérification des valeurs null / vides dans les colonnes supplémentaires\n")

for col in extra_cols:
    nan_count = agencies_df[col].isna().sum()
    empty_count = (agencies_df[col].astype(str).str.strip() == "").sum()
    total = nan_count + empty_count

    print(f"🔹 {col} : NaN = {nan_count}, vides = {empty_count}, TOTAL = {total}")

📊 Vérification des valeurs null / vides dans les colonnes supplémentaires

🔹 agency_url : NaN = 0, vides = 0, TOTAL = 0
🔹 agency_lang : NaN = 2040, vides = 0, TOTAL = 2040
🔹 agency_phone : NaN = 1780, vides = 0, TOTAL = 1780
🔹 agency_fare_url : NaN = 2302, vides = 0, TOTAL = 2302
🔹 agency_email : NaN = 2323, vides = 0, TOTAL = 2323
🔹 agency_branding_url : NaN = 2371, vides = 0, TOTAL = 2371
🔹 source_folder : NaN = 0, vides = 0, TOTAL = 0

In [13]:
# 📌 Colonnes à supprimer (inutile pour ton projet)
cols_to_drop = ["agency_branding_url", "agency_fare_url", "agency_email"]

# Supprimer les colonnes
agencies_df = agencies_df.drop(columns=cols_to_drop)

# Vérifier le résultat
print("Colonnes restantes :", agencies_df.columns.tolist())

Colonnes restantes : ['agency_id', 'agency_name', 'agency_url', 'agency_timezone', 'agency_lang', 'agency_phone', 'source_folder']

In [14]:
# 🔹 Colonnes facultatives
optional_cols = ["agency_lang", "agency_phone", "agency_url"]

# 1️⃣ Remplir les valeurs vides ou NaN
# - agency_lang : mettre 'es' par défaut si vide
# - agency_phone et agency_url : laisser NaN
import numpy as np

agencies_df["agency_lang"] = agencies_df["agency_lang"].fillna("es")
agencies_df["agency_phone"] = agencies_df["agency_phone"].replace("", np.nan)
agencies_df["agency_url"] = agencies_df["agency_url"].replace("", np.nan)

# 2️⃣ Nettoyer les numéros de téléphone
# Supprimer tous les caractères non numériques sauf '+' au début
import re

def clean_phone(phone):
    if pd.isna(phone):
        return np.nan
    phone = str(phone).strip()
    phone = re.sub(r"[^\d+]", "", phone)
    return phone

agencies_df["agency_phone"] = agencies_df["agency_phone"].apply(clean_phone)

# 3️⃣ Vérifier le résultat
print(agencies_df.head())

    agency_id                  agency_name                   agency_url  \
0  a-28005890                         AISA  https://www.aisa-grupo.com/
1         300                         ALSA           http://www.alsa.es
2     Aucorsa  Autobuses de Córdoba - S.A.       https://www.aucorsa.es
3       autna                        AUTNA       https://www.autna.com/
4           1                     Álavabus      https://alavabus.eus/es

  agency_timezone agency_lang   agency_phone  \
0   Europe/Madrid          es    34918752018
1   Europe/Madrid          es      902422242
2   Europe/Madrid          es      957764676
3   Europe/Madrid          es  0034986288030
4   Europe/Madrid          es      945182060

                                     source_folder
0  AISA (Bus Madrid-Aranda de Duero-Burgo de Osma)
1                                       ALSA buses
2             AUCORSA (Autobuses de Córdoba S.A.)
3                                         AUTNA SL
4                                         Alavabus

In [16]:
# 🔹 Nettoyage avancé des colonnes obligatoires
def clean_obligatory_columns(df):
    # agency_id : minuscule, strip
    df["agency_id"] = df["agency_id"].astype(str).str.strip().str.lower()

    # agency_name : strip, optionnel title()
    df["agency_name"] = df["agency_name"].astype(str).str.strip().str.title().str.lower()

    # agency_timezone : strip, minuscule
    df["agency_timezone"] = df["agency_timezone"].astype(str).str.strip().str.lower()

    return df

agencies_df = clean_obligatory_columns(agencies_df)

# Vérifier le résultat
print(agencies_df.head())

    agency_id                  agency_name                   agency_url  \
0  a-28005890                         aisa  https://www.aisa-grupo.com/
1         300                         alsa           http://www.alsa.es
2     aucorsa  autobuses de córdoba - s.a.       https://www.aucorsa.es
3       autna                        autna       https://www.autna.com/
4           1                     álavabus      https://alavabus.eus/es

  agency_timezone agency_lang   agency_phone  \
0   europe/madrid          es    34918752018
1   europe/madrid          es      902422242
2   europe/madrid          es      957764676
3   europe/madrid          es  0034986288030
4   europe/madrid          es      945182060

                                     source_folder
0  AISA (Bus Madrid-Aranda de Duero-Burgo de Osma)
1                                       ALSA buses
2             AUCORSA (Autobuses de Córdoba S.A.)
3                                         AUTNA SL
4                                         Alavabus

In [17]:
# Convertir toutes les langues en minuscules
agencies_df['agency_lang'] = agencies_df['agency_lang'].str.lower()

In [18]:
cols_order = ['agency_id', 'agency_name', 'agency_timezone',
              'agency_lang', 'agency_phone', 'agency_url', 'source_folder']
agencies_df = agencies_df[cols_order]

In [19]:
agencies_df["agency_id"] = agencies_df["agency_id"].astype(str)

In [20]:
# Garder uniquement les chiffres
agencies_df["agency_phone"] = agencies_df["agency_phone"].astype(str).str.replace(r"\D", "", regex=True)

# Garder seulement les numéros de 9 chiffres
agencies_df["agency_phone"] = agencies_df["agency_phone"].apply(
    lambda x: x if len(x) == 9 else None
)

In [21]:
import numpy as np

# 1. Convertir en string et enlever tout sauf les chiffres
agencies_df["agency_phone"] = agencies_df["agency_phone"].astype(str).str.replace(r"\D", "", regex=True)

# 2. Remplacer "nan", "" et "None" par NaN réel
agencies_df["agency_phone"].replace(["", "nan", "None"], np.nan, inplace=True)

# 3. Garder seulement les numéros de 9 chiffres, sinon NaN
agencies_df["agency_phone"] = agencies_df["agency_phone"].apply(
    lambda x: x if isinstance(x, str) and len(x) == 9 else np.nan
)

/tmp/ipython-input-1045780983.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  agencies_df["agency_phone"].replace(["", "nan", "None"], np.nan, inplace=True)

In [22]:
# Repérer les doublons exacts
doublons = agencies_df[agencies_df.duplicated(keep=False)]

# Afficher les lignes doublées
print(doublons)

Empty DataFrame
Columns: [agency_id, agency_name, agency_timezone, agency_lang, agency_phone, agency_url, source_folder]
Index: []

In [23]:
# Afficher les 10 premières lignes
agencies_df.head(10)

,agency_id,agency_name,agency_timezone,agency_lang,agency_phone,agency_url,source_folder
0,a-28005890,aisa,europe/madrid,es,NaN,https://www.aisa-grupo.com/,AISA (Bus Madrid-Aranda de Duero-Burgo de Osma)
1,300,alsa,europe/madrid,es,902422242,http://www.alsa.es,ALSA buses
2,aucorsa,autobuses de córdoba - s.a.,europe/madrid,es,957764676,https://www.aucorsa.es,AUCORSA (Autobuses de Córdoba S.A.)
3,autna,autna,europe/madrid,es,NaN,https://www.autna.com/,AUTNA SL
4,1,álavabus,europe/madrid,es,945182060,https://alavabus.eus/es,Alavabus
5,2,transporte comarcal,europe/madrid,es,945182060,https://alavabus.eus/es,Alavabus
6,autos alvarez,autos alvarez de viajeros sl,europe/madrid,es,980620501,http://vulpeti.com/moderniza/B49122856.zip,Alvarez Travelers Coaches
7,ancebus,"ancebus, sl",europe/madrid,es,NaN,http://www.ancebus.com/,Ancebus
8,13,auif,europe/madrid,es,943633111,http://www.auif.es/,Auif Irunbus (Lurraldebus)
9,1,autocares baraza,europe/madrid,es,950390311,http://www.autocaresbaraza.com,Autocares Baraza (Baraza Coaches)

In [24]:
import os

# Dossier principal contenant les sous-dossiers
main_folder = "/content/drive/MyDrive/GTFS_CLEAN"  # mettre ton chemin exact

# Parcourir toutes les valeurs uniques de source_folder
for subfolder_name in agencies_df["source_folder"].unique():
    subfolder_path = os.path.join(main_folder, subfolder_name)

    if not os.path.exists(subfolder_path):
        os.makedirs(subfolder_path)

    # Sélectionner uniquement les lignes correspondant à ce sous-dossier
    df_subset = agencies_df[agencies_df["source_folder"] == subfolder_name].copy()

    # Supprimer la colonne source_folder
    if "source_folder" in df_subset.columns:
        df_subset.drop(columns=["source_folder"], inplace=True)

    # Définir le chemin du fichier
    output_file = os.path.join(subfolder_path, "agency_clean.txt")

    # Sauvegarder le dataframe filtré
    df_subset.to_csv(output_file, index=False, sep=",", encoding="utf-8")

    print(f"📥 Fichier créé : {output_file} ({len(df_subset)} lignes)")

📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/AISA (Bus Madrid-Aranda de Duero-Burgo de Osma)/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/ALSA buses/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/AUCORSA (Autobuses de Córdoba S.A.)/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/AUTNA SL/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Alavabus/agency_clean.txt (2 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Alvarez Travelers Coaches/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Ancebus/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Auif Irunbus (Lurraldebus)/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Autocares Baraza (Baraza Coaches)/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Autocares Rías Baixas (Rías Baixas Coaches)/agency_clean.txt (2 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Autocorb Coaches/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Autoridad de Transporte Metropolitano del Area de Barcelona (ATM) Buses and trains in Catalonia (full version)/agency_clean.txt (177 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Avanza Grupo (Ávila city bus)/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Avanza Grupo (Huesca city bus)/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Avanza Grupo (Mataró city bus)/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Avanza Grupo (Segovia city bus)/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Avanza Grupo (Soria city bus)/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Avanza Grupo (VAC-124. Huesca-Lleida with branches)/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Avanza Grupo (VAC-245. Huesca-Barcelona)/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Àrea Metropolitana de Barcelona (AMB)/agency_clean.txt (10 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Bermibusa/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Bizkaibus/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/BlaBlaCar Bus/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Catalonia Area de Barcelona/agency_clean.txt (165 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/City Council of Las Palmas de Gran Canaria (city bus)/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Collegamenti marittimi Grandi Navi Veloci/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Collegamenti marittimi Grimaldi/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Consorcio Regional de Transportes de Madrid CRTM Intercity Buses (Madrid Intercity Bus)/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Consorcio Regional de Transportes de Madrid CRTM Light Rail Network (Red de Metro Ligero)/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Consorcio Regional de Transportes de Madrid CRTM Madrid City Bus (Autobus urbano de Madrid)/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Consorcio Regional de Transportes de Madrid Métro Ligero de Madrid/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Consorcio Regional de Transportes de Madrid Réseau de navettes CRTM (Red de Cercanías)/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Costa Coaches/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Cots Alsina/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Direxis Masats/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Direxis TGO (Transportes Generales de Olesa)/agency_clean.txt (2 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/EMT Tarragona/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/El Transbordador de Vizcaya/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/El Transbordador de Vizcaya (Bizkaia Bridge Ferry)/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Empresa Municipal de Transportes de Madrid (EMT Madrid)/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Empresa Municipal de Transportes de Valencia (EMT Valencia)/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Empresa Municipal de Transports Urbans de Palma de Mallorca/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Erandio City Council (Erandio! Busa)/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Etxebarri Town Hall/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Euskotren/agency_clean.txt (4 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/FGV - Generalitat Valenciana Metro de Valencia/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/FGV - Generalitat Valenciana Trains and trams in Alicante and the Costa Blanca/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Ferry Fred. Olsen (Fred Olsen Express)/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Funiculaire de Artxanda/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Generalitat of Catalonia (Intercity bus)/agency_clean.txt (1486 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Gobierno de Cantabria (Bus en Cantabrie)/agency_clean.txt (11 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Granada City Council (Granada city bus)/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Guaguas Municipales/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Junta de Extremadura (Bus du gouvernement régional d’Estrémadure)/agency_clean.txt (32 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Kbus (Barakaldo urban)/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/La Burundesa_SA/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/La Coruña Tram Company SA/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/La Regional Vallisoletana SA/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/La Veloz SA (Buses from the Belchite countryside area to Zaragoza (C12))/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Lázara Coaches/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Leioa City Council (Lejoan Busa)/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Lurraldebus - Hernani Urban (bus urbain d’Hernani)/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Lurraldebus Arrasate/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Lurraldebus Eibar/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Lurraldebus Ekialdebus/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Lurraldebus Euskotren bus/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Lurraldebus Goierrialdea/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Lurraldebus Guipuzcoana (La Guipuzcoana)/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Lurraldebus Lasarte/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Lurraldebus Oiartzun (Xorrola)/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Lurraldebus Pesa/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Lurraldebus TBH (Interurban Tolosa Buruntzaldea)/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Lurraldebus Tolosaldea/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Lurraldebus Urbano de Errentería (Errenteria Urbanoa)/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Lurraldebus Zarautz/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Metro de Sevilla/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/MetroValencia/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Metropolitano de Tenerife (Metrotenerife)/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Métro Bilbao/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Métro de Madrid/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/NVBW - Nahverkehrsgesellschaft Baden-Württemberg mbH/agency_clean.txt (308 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Nouvelle-Aquitaine Mobilités/agency_clean.txt (46 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Oñati urbain (Oñatiko herribusa)/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Ouigo/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Palma City Council (Palma de Mallorca city bus)/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Pinto City Council/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Rafael Nadal Coaches/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Réseau interurbain liO Occitanie/agency_clean.txt (17 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Rodil/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Sopela Town Hall/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/TIB Transports de les Illes Balears - CTM Transport Consortium of Mallorcam (Public transport on the island of Mallorca)/agency_clean.txt (9 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/TIB Transports of the Balearic Islands - CIE Consell Insular d'Eivissa (Ibiza Island Bus)/agency_clean.txt (7 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/TIB Transports of the Balearic Islands - CIME Consell Insular de Menorca (Menorca Island Bus)/agency_clean.txt (5 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/TMESA/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/TRAM Alicante/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/TUS (Transportes Urbanos de Santander)/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/TUSSAM (Seville bus and tram)/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Tolosa City Council (Urbano de Tolosa)/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/TranspRober/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Transports Municipals del Gironés SAU (TMG) Girona city bus/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Transports Municipaux D’Egara (TMESA) Terrassa bus urbain/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Vectalia Movilidad (bus de la ville de Cáceres)/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Viagón Coaches/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Xunta de Galicia Buses/agency_clean.txt (1 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/dBus (Donostiabus)/agency_clean.txt (1 lignes)

In [25]:
import os
import pandas as pd

# Dossier principal contenant les sous-dossiers
GTFS_CLEAN = "/content/drive/MyDrive/GTFS_CLEAN"  # mettre ton chemin exact

all_stops = []  # liste pour stocker tous les df stops.txt

# Parcourir les sous-dossiers
for subfolder in sorted(os.listdir(GTFS_CLEAN)):
    folder_path = os.path.join(GTFS_CLEAN, subfolder)

    # Vérifier que c'est bien un dossier
    if not os.path.isdir(folder_path):
        continue

    stops_path = os.path.join(folder_path, "stops.txt")

    # Vérifier que le fichier stops.txt existe
    if os.path.exists(stops_path):
        try:
            df = pd.read_csv(stops_path, encoding="utf-8", on_bad_lines="skip")

            # Ajouter la colonne pour savoir d'où vient la ligne
            df["source_folder"] = subfolder

            # Ajouter le dataframe à la liste
            all_stops.append(df)

            print(f"📥 stops.txt chargé depuis : {subfolder} ({len(df)} lignes)")
        except Exception as e:
            print(f"⚠️ Erreur lecture dans {subfolder}: {e}")
    else:
        print(f"❌ Aucun stops.txt dans : {subfolder}")

# Combiner tous les dataframes en un seul si nécessaire
if all_stops:
    stops_df = pd.concat(all_stops, ignore_index=True)
    print(f"\n✅ stops.txt combinés : {len(stops_df)} lignes au total")
else:
    print("\n❌ Aucun stops.txt trouvé dans tous les sous-dossiers")

📥 stops.txt chargé depuis : AISA (Bus Madrid-Aranda de Duero-Burgo de Osma) (36 lignes)
📥 stops.txt chargé depuis : ALSA buses (11470 lignes)
📥 stops.txt chargé depuis : AUCORSA (Autobuses de Córdoba S.A.) (613 lignes)
📥 stops.txt chargé depuis : AUTNA SL (9 lignes)
📥 stops.txt chargé depuis : Alavabus (678 lignes)
📥 stops.txt chargé depuis : Alvarez Travelers Coaches (65 lignes)
📥 stops.txt chargé depuis : Ancebus (26 lignes)
📥 stops.txt chargé depuis : Auif Irunbus (Lurraldebus) (72 lignes)
📥 stops.txt chargé depuis : Autocares Baraza (Baraza Coaches) (50 lignes)
📥 stops.txt chargé depuis : Autocares Rías Baixas (Rías Baixas Coaches) (2549 lignes)
📥 stops.txt chargé depuis : Autocorb Coaches (170 lignes)
📥 stops.txt chargé depuis : Autoridad de Transporte Metropolitano del Area de Barcelona (ATM) Buses and trains in Catalonia (full version) (28410 lignes)
📥 stops.txt chargé depuis : Avanza Grupo (Ávila city bus) (194 lignes)
📥 stops.txt chargé depuis : Avanza Grupo (Huesca city bus) (68 lignes)
📥 stops.txt chargé depuis : Avanza Grupo (Mataró city bus) (145 lignes)
📥 stops.txt chargé depuis : Avanza Grupo (Segovia city bus) (155 lignes)
📥 stops.txt chargé depuis : Avanza Grupo (Soria city bus) (81 lignes)
📥 stops.txt chargé depuis : Avanza Grupo (VAC-124. Huesca-Lleida with branches) (57 lignes)
📥 stops.txt chargé depuis : Avanza Grupo (VAC-245. Huesca-Barcelona) (7 lignes)
📥 stops.txt chargé depuis : Àrea Metropolitana de Barcelona (AMB) (4815 lignes)
📥 stops.txt chargé depuis : Bermibusa (20 lignes)
📥 stops.txt chargé depuis : Bizkaibus (2304 lignes)
📥 stops.txt chargé depuis : BlaBlaCar Bus (346 lignes)
📥 stops.txt chargé depuis : Catalonia Area de Barcelona (24076 lignes)
📥 stops.txt chargé depuis : City Council of Las Palmas de Gran Canaria (city bus) (848 lignes)
📥 stops.txt chargé depuis : Collegamenti marittimi Grandi Navi Veloci (36 lignes)
📥 stops.txt chargé depuis : Collegamenti marittimi Grimaldi (36 lignes)
📥 stops.txt chargé depuis : Consorcio Regional de Transportes de Madrid CRTM Intercity Buses (Madrid Intercity Bus) (8392 lignes)
📥 stops.txt chargé depuis : Consorcio Regional de Transportes de Madrid CRTM Light Rail Network (Red de Metro Ligero) (78 lignes)
📥 stops.txt chargé depuis : Consorcio Regional de Transportes de Madrid CRTM Madrid City Bus (Autobus urbano de Madrid) (8392 lignes)
📥 stops.txt chargé depuis : Consorcio Regional de Transportes de Madrid Métro Ligero de Madrid (78 lignes)
📥 stops.txt chargé depuis : Consorcio Regional de Transportes de Madrid Réseau de navettes CRTM (Red de Cercanías) (97 lignes)
📥 stops.txt chargé depuis : Costa Coaches (446 lignes)
📥 stops.txt chargé depuis : Cots Alsina (97 lignes)
📥 stops.txt chargé depuis : Direxis Masats (161 lignes)
📥 stops.txt chargé depuis : Direxis TGO (Transportes Generales de Olesa) (419 lignes)
📥 stops.txt chargé depuis : EMT Tarragona (408 lignes)
📥 stops.txt chargé depuis : El Transbordador de Vizcaya (2 lignes)
📥 stops.txt chargé depuis : El Transbordador de Vizcaya (Bizkaia Bridge Ferry) (2 lignes)
📥 stops.txt chargé depuis : Empresa Municipal de Transportes de Madrid (EMT Madrid) (4917 lignes)
📥 stops.txt chargé depuis : Empresa Municipal de Transportes de Valencia (EMT Valencia) (1148 lignes)
📥 stops.txt chargé depuis : Empresa Municipal de Transports Urbans de Palma de Mallorca (873 lignes)
📥 stops.txt chargé depuis : Erandio City Council (Erandio! Busa) (55 lignes)
📥 stops.txt chargé depuis : Etxebarri Town Hall (24 lignes)
📥 stops.txt chargé depuis : Euskotren (798 lignes)
📥 stops.txt chargé depuis : FGV - Generalitat Valenciana Metro de Valencia (144 lignes)
📥 stops.txt chargé depuis : FGV - Generalitat Valenciana Trains and trams in Alicante and the Costa Blanca (70 lignes)
📥 stops.txt chargé depuis : Ferry Fred. Olsen (Fred Olsen Express) (13 lignes)
📥 stops.txt chargé depuis : Funiculaire de Artxanda (2 lignes)
📥 stops.txt chargé depuis : Generalitat of Catalonia (Intercity bus) (8715 lignes)
📥 stops.txt chargé depuis : Gobierno de Cantabria (Bus en Cantabrie) (973 lignes)
📥 stops.txt chargé depuis : Granada City Council (Granada city bus) (680 lignes)
📥 stops.txt chargé depuis : Guaguas Municipales (848 lignes)
📥 stops.txt chargé depuis : Junta de Extremadura (Bus du gouvernement régional d’Estrémadure) (520 lignes)
📥 stops.txt chargé depuis : Kbus (Barakaldo urban) (88 lignes)
📥 stops.txt chargé depuis : La Burundesa_SA (158 lignes)
📥 stops.txt chargé depuis : La Coruña Tram Company SA (535 lignes)
📥 stops.txt chargé depuis : La Regional Vallisoletana SA (66 lignes)
📥 stops.txt chargé depuis : La Veloz SA (Buses from the Belchite countryside area to Zaragoza (C12)) (37 lignes)
📥 stops.txt chargé depuis : Lázara Coaches (1321 lignes)
📥 stops.txt chargé depuis : Leioa City Council (Lejoan Busa) (30 lignes)
📥 stops.txt chargé depuis : Lurraldebus - Hernani Urban (bus urbain d’Hernani) (27 lignes)
📥 stops.txt chargé depuis : Lurraldebus Arrasate (54 lignes)
📥 stops.txt chargé depuis : Lurraldebus Eibar (38 lignes)
📥 stops.txt chargé depuis : Lurraldebus Ekialdebus (229 lignes)
📥 stops.txt chargé depuis : Lurraldebus Euskotren bus (234 lignes)
📥 stops.txt chargé depuis : Lurraldebus Goierrialdea (201 lignes)
📥 stops.txt chargé depuis : Lurraldebus Guipuzcoana (La Guipuzcoana) (178 lignes)
📥 stops.txt chargé depuis : Lurraldebus Lasarte (38 lignes)
📥 stops.txt chargé depuis : Lurraldebus Oiartzun (Xorrola) (16 lignes)
📥 stops.txt chargé depuis : Lurraldebus Pesa (0 lignes)
📥 stops.txt chargé depuis : Lurraldebus TBH (Interurban Tolosa Buruntzaldea) (238 lignes)
📥 stops.txt chargé depuis : Lurraldebus Tolosaldea (234 lignes)
📥 stops.txt chargé depuis : Lurraldebus Urbano de Errentería (Errenteria Urbanoa) (82 lignes)
📥 stops.txt chargé depuis : Lurraldebus Zarautz (34 lignes)
📥 stops.txt chargé depuis : Metro de Sevilla (42 lignes)
📥 stops.txt chargé depuis : MetroValencia (144 lignes)
📥 stops.txt chargé depuis : Metropolitano de Tenerife (Metrotenerife) (25 lignes)
📥 stops.txt chargé depuis : Métro Bilbao (191 lignes)
📥 stops.txt chargé depuis : Métro de Madrid (1050 lignes)
📥 stops.txt chargé depuis : NVBW - Nahverkehrsgesellschaft Baden-Württemberg mbH (61509 lignes)
📥 stops.txt chargé depuis : Nouvelle-Aquitaine Mobilités (43189 lignes)
📥 stops.txt chargé depuis : Oñati urbain (Oñatiko herribusa) (32 lignes)
📥 stops.txt chargé depuis : Ouigo (16 lignes)
📥 stops.txt chargé depuis : Palma City Council (Palma de Mallorca city bus) (873 lignes)
📥 stops.txt chargé depuis : Pinto City Council (59 lignes)
📥 stops.txt chargé depuis : Rafael Nadal Coaches (3 lignes)
📥 stops.txt chargé depuis : Réseau interurbain liO Occitanie (12288 lignes)
📥 stops.txt chargé depuis : Rodil (81 lignes)
📥 stops.txt chargé depuis : Sopela Town Hall (18 lignes)
📥 stops.txt chargé depuis : TIB Transports de les Illes Balears - CTM Transport Consortium of Mallorcam (Public transport on the island of Mallorca) (704 lignes)
📥 stops.txt chargé depuis : TIB Transports of the Balearic Islands - CIE Consell Insular d'Eivissa (Ibiza Island Bus) (592 lignes)
📥 stops.txt chargé depuis : TIB Transports of the Balearic Islands - CIME Consell Insular de Menorca (Menorca Island Bus) (196 lignes)
📥 stops.txt chargé depuis : TMESA (350 lignes)
📥 stops.txt chargé depuis : TRAM Alicante (70 lignes)
📥 stops.txt chargé depuis : TUS (Transportes Urbanos de Santander) (460 lignes)
📥 stops.txt chargé depuis : TUSSAM (Seville bus and tram) (1046 lignes)
📥 stops.txt chargé depuis : Tolosa City Council (Urbano de Tolosa) (26 lignes)
📥 stops.txt chargé depuis : TranspRober (680 lignes)
📥 stops.txt chargé depuis : Transports Municipals del Gironés SAU (TMG) Girona city bus (250 lignes)
📥 stops.txt chargé depuis : Transports Municipaux D’Egara (TMESA) Terrassa bus urbain (350 lignes)
📥 stops.txt chargé depuis : Vectalia Movilidad (bus de la ville de Cáceres) (237 lignes)
📥 stops.txt chargé depuis : Viagón Coaches (62 lignes)
📥 stops.txt chargé depuis : Xunta de Galicia Buses (26897 lignes)
📥 stops.txt chargé depuis : dBus (Donostiabus) (535 lignes)

✅ stops.txt combinés : 271501 lignes au total

/tmp/ipython-input-4005143002.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stops_df = pd.concat(all_stops, ignore_index=True)

In [26]:
stops_df.sample(10)

,stop_id,stop_code,stop_name,stop_lat,stop_lon,zone_id,stop_url,location_type,parent_station,stop_timezone,source_folder,stop_desc,wheelchair_boarding,tts_stop_name,level_id,platform_code,out_of_service
51921,1147,48002030,SANTA JULIANA (1147),43.318133,-3.079989,3,NaN,0.0,NaN,Europe/Madrid,Bizkaibus,NaN,1.0,NaN,0,NaN,NaN
202832,MOBIITI:StopPlace:76305,NaN,Fenêtre,45.754772,-0.635868,NaN,NaN,1.0,NaN,NaN,Nouvelle-Aquitaine Mobilités,NaN,2.0,NaN,NaN,NaN,NaN
124851,de:08111:6091_Parent,NaN,Obertürkheim,48.761752,9.268170,NaN,NaN,1.0,NaN,NaN,NVBW - Nahverkehrsgesellschaft Baden-Württemb...,NaN,NaN,NaN,NaN,NaN,NaN
4978,0006209600000001,NaN,Isaac Peral(Esc.Ofi.Idionas)-P,42.002429,-4.522089,NaN,NaN,0.0,NaN,Europe/Madrid,ALSA buses,NaN,NaN,NaN,NaN,NaN,NaN
236597,4600866,NaN,PRADINES - Les Châtaigneraies,44.468103,1.405886,NaN,NaN,0.0,46S00866,NaN,Réseau interurbain liO Occitanie,arrêt commercial,0.0,NaN,NaN,NaN,NaN
190490,MOBIITI:StopPlace:47213,NaN,Alfred de Vigny,44.830231,-0.633958,NaN,NaN,1.0,NaN,NaN,Nouvelle-Aquitaine Mobilités,NaN,1.0,NaN,NaN,NaN,NaN
146407,de:08221:1104:0:11,NaN,"Ziegelhausen, Hirtenaue",49.426302,8.759796,NaN,NaN,NaN,NaN,NaN,NVBW - Nahverkehrsgesellschaft Baden-Württemb...,NaN,0.0,NaN,NaN,NaN,NaN
263797,SP34787,1007757,Reboreda (Boca Do Valo),42.273337,-8.594190,36045-66,NaN,NaN,NaN,NaN,Xunta de Galicia Buses,NaN,NaN,NaN,NaN,NaN,NaN
170786,de:08417:30524:0:2,NaN,Tailfingen Neuweiler Rad,48.262266,9.054272,NaN,NaN,NaN,NaN,NaN,NVBW - Nahverkehrsgesellschaft Baden-Württemb...,NaN,0.0,NaN,NaN,NaN,NaN
114687,6,NaN,"León y Castillo, 13",28.109872,-15.418223,NaN,NaN,NaN,NaN,NaN,Guaguas Municipales,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
import pandas as pd

# Colonnes obligatoires
mandatory_cols = ["stop_id", "stop_name", "stop_lat", "stop_lon"]

# Fonction pour compter les "vraies" valeurs manquantes
def count_missing(series):
    # Convertir en str pour détecter les espaces
    return series.isna().sum() + (series.astype(str).str.strip() == "").sum()

# Appliquer la fonction à chaque colonne obligatoire
missing_summary = {col: count_missing(stops_df[col]) for col in mandatory_cols}

# Afficher le résultat
print("Nombre total de valeurs manquantes, NaN ou vides par colonne obligatoire :\n")
for col, count in missing_summary.items():
    print(f"{col} : {count}")

Nombre total de valeurs manquantes, NaN ou vides par colonne obligatoire :

stop_id : 0
stop_name : 0
stop_lat : 0
stop_lon : 0

In [28]:
# Toutes les colonnes sauf les obligatoires
extra_cols = [col for col in stops_df.columns if col not in ["stop_id", "stop_name", "stop_lat", "stop_lon"]]

# Fonction pour compter les valeurs manquantes, NaN ou vides
def count_missing(series):
    return series.isna().sum() + (series.astype(str).str.strip() == "").sum()

# Nombre total de lignes dans le dataframe
total_rows = len(stops_df)

# Appliquer la fonction à toutes les colonnes supplémentaires et calculer le pourcentage
missing_summary_extra = {col: (count_missing(stops_df[col]), round(count_missing(stops_df[col])/total_rows*100, 2)) for col in extra_cols}

# Afficher le résultat de façon lisible
print("Nombre et pourcentage de valeurs manquantes, NaN ou vides par colonne supplémentaire :\n")
for col, (count, pct) in missing_summary_extra.items():
    print(f"{col} : {count} lignes manquantes ({pct}%)")

Nombre et pourcentage de valeurs manquantes, NaN ou vides par colonne supplémentaire :

stop_code : 145457 lignes manquantes (53.58%)
zone_id : 214207 lignes manquantes (78.9%)
stop_url : 230789 lignes manquantes (85.0%)
location_type : 102736 lignes manquantes (37.84%)
parent_station : 226541 lignes manquantes (83.44%)
stop_timezone : 238362 lignes manquantes (87.79%)
source_folder : 0 lignes manquantes (0.0%)
stop_desc : 209435 lignes manquantes (77.14%)
wheelchair_boarding : 72459 lignes manquantes (26.69%)
tts_stop_name : 270823 lignes manquantes (99.75%)
level_id : 267721 lignes manquantes (98.61%)
platform_code : 263779 lignes manquantes (97.16%)
out_of_service : 266686 lignes manquantes (98.23%)

In [29]:
len(stops_df)

271501

In [30]:
import pandas as pd

# Pourcentage limite pour supprimer la colonne
threshold = 0.7

# Calculer le pourcentage de valeurs manquantes (NaN ou vides) par colonne
def missing_percentage(series):
    total = len(series)
    missing = series.isna().sum() + (series.astype(str).str.strip() == "").sum()
    return missing / total

# Colonnes à supprimer si plus de 70 % manquantes, sauf stop_timezone
cols_to_drop = [col for col in stops_df.columns
                if col != "stop_timezone" and missing_percentage(stops_df[col]) > threshold]

# Supprimer les colonnes
stops_df.drop(columns=cols_to_drop, inplace=True)
print(f"Colonnes supprimées (>70% manquantes) : {cols_to_drop}")

# Remplacer les NaN ou vides dans stop_timezone par 'Europe/Madrid'
stops_df["stop_timezone"] = stops_df["stop_timezone"].replace(to_replace=[None, "", "nan", "NaN"], value="Europe/Madrid")
stops_df["stop_timezone"].fillna("Europe/Madrid", inplace=True)

print("✅ Colonnes nettoyées avec succès")

Colonnes supprimées (>70% manquantes) : ['zone_id', 'stop_url', 'parent_station', 'stop_desc', 'tts_stop_name', 'level_id', 'platform_code', 'out_of_service']
✅ Colonnes nettoyées avec succès

/tmp/ipython-input-3486416132.py:22: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  stops_df["stop_timezone"].fillna("Europe/Madrid", inplace=True)

In [31]:
stops_df.sample(10)

,stop_id,stop_code,stop_name,stop_lat,stop_lon,location_type,stop_timezone,source_folder,wheelchair_boarding
9067,0003072000000001,NaN,Ll.I. El Pi - Plz Olivera-Sols,41.976917,1.555571,0.0,Europe/Madrid,ALSA buses,NaN
187052,MOBIITI:Quay:114795,36801,Pré des Chambauds,45.722263,0.163153,0.0,Europe/Madrid,Nouvelle-Aquitaine Mobilités,2.0
216015,MOBIITI:Quay:74409,231,Mairie de Billère,43.301479,-0.397078,0.0,Europe/Madrid,Nouvelle-Aquitaine Mobilités,2.0
179687,de:09677:28592:0:1,NaN,Lengfurt Wasenberg,49.818127,9.599702,NaN,Europe/Madrid,NVBW - Nahverkehrsgesellschaft Baden-Württemb...,0.0
240163,556,613,Can Clavos (613),38.957623,1.445712,NaN,Europe/Madrid,TIB Transports of the Balearic Islands - CIE C...,NaN
267375,SP39058,5012528,CORTIÑAS,42.750241,-7.527770,NaN,Europe/Madrid,Xunta de Galicia Buses,NaN
73355,TMB_2.2323.682500,2323,Pl Miquel Casablancas,41.439710,2.186420,0.0,Europe/Madrid,Catalonia Area de Barcelona,0.0
22148,CAS_7257,3462,PL. DE LA VILA/PG. DE LES MONGES,41.574707,2.483657,0.0,Europe/Madrid,Autoridad de Transporte Metropolitano del Area...,0.0
196141,MOBIITI:Quay:77522,7919835A,PUY LARGE,46.746693,-0.588237,0.0,Europe/Madrid,Nouvelle-Aquitaine Mobilités,2.0
19644,AMB_112243,112243,Jardins de la Pau,41.321290,2.097317,0.0,Europe/Madrid,Autoridad de Transporte Metropolitano del Area...,0.0

In [33]:
stops_df["wheelchair_boarding"].value_counts(dropna=False)

wheelchair_boarding
0.0    130956
NaN     72459
2.0     48945
1.0     19141
Name: count, dtype: int64

In [35]:
stops_df["wheelchair_boarding"] = stops_df["wheelchair_boarding"].fillna(0)

In [36]:
stops_df["wheelchair_boarding"].value_counts(dropna=False)

wheelchair_boarding
0.0    203415
2.0     48945
1.0     19141
Name: count, dtype: int64

In [38]:
stops_df["wheelchair_boarding"] = stops_df["wheelchair_boarding"].astype(int)

In [39]:
# Normaliser stop_id en minuscules
stops_df['stop_id'] = stops_df['stop_id'].astype(str).str.lower()

In [40]:
# Mettre en minuscules et nettoyer les espaces multiples
stops_df["stop_name"] = stops_df["stop_name"].astype(str)  # s'assurer que c'est du texte
stops_df["stop_name"] = stops_df["stop_name"].str.lower()  # tout en minuscules
stops_df["stop_name"] = stops_df["stop_name"].str.strip()  # enlever espaces au début et à la fin
stops_df["stop_name"] = stops_df["stop_name"].str.replace(r"\s+", " ", regex=True)  # remplacer plusieurs espaces par un seul

In [41]:
stops_df["stop_id"] = stops_df["stop_id"].str.lower()

In [42]:
stops_df["stop_id"] = stops_df["stop_id"].str.strip()

In [43]:
stops_df.sample(10)

,stop_id,stop_code,stop_name,stop_lat,stop_lon,location_type,stop_timezone,source_folder,wheelchair_boarding
230305,30s14558,NaN,saint-dionisy - le soldat,43.804531,4.224458,1.0,Europe/Madrid,Réseau interurbain liO Occitanie,0
138850,de:08128:12914:0:rio,NaN,"niederstetten, ziegelmühle",49.401768,9.919790,NaN,Europe/Madrid,NVBW - Nahverkehrsgesellschaft Baden-Württemb...,0
217173,mobiiti:stopplace:77103,NaN,lavoisier,45.180931,0.743143,1.0,Europe/Madrid,Nouvelle-Aquitaine Mobilités,2
16089,als_0000897700000001,NaN,vilanova de la sal,41.878124,0.785973,0.0,Europe/Madrid,Autoridad de Transporte Metropolitano del Area...,0
229985,1006413,NaN,puimisson - pierre plantee,43.439663,3.212515,1.0,Europe/Madrid,Réseau interurbain liO Occitanie,0
239480,1574,31056,llucmajor est 1 (31056),39.488796,2.898646,NaN,Europe/Madrid,TIB Transports de les Illes Balears - CTM Tran...,0
140991,de:08136:3415:0:2,NaN,"lindach, paulushaus",48.837864,9.843766,NaN,Europe/Madrid,NVBW - Nahverkehrsgesellschaft Baden-Württemb...,0
131304,de:08118:7440:0:4,NaN,bietigheim fr.-ebert-straße,48.962737,9.141885,NaN,Europe/Madrid,NVBW - Nahverkehrsgesellschaft Baden-Württemb...,0
246316,sp12471,1002037,as sinas,42.576394,-8.817147,NaN,Europe/Madrid,Xunta de Galicia Buses,0
33881,olo_62,NaN,ceip st. roc,42.170719,2.469550,0.0,Europe/Madrid,Autoridad de Transporte Metropolitano del Area...,0

In [44]:
# Remplacer les NaN et vides par 0
stops_df['location_type'] = stops_df['location_type'].fillna(0)

# Supprimer les espaces éventuels et convertir en entier
stops_df['location_type'] = stops_df['location_type'].astype(str).str.strip()

# Remplacer les valeurs non numériques par 0
stops_df['location_type'] = stops_df['location_type'].apply(lambda x: x if x.isdigit() else '0')

# Convertir en entier
stops_df['location_type'] = stops_df['location_type'].astype(int)

# Vérifier les valeurs uniques pour s'assurer qu'elles sont correctes
print("Valeurs uniques dans location_type :", stops_df['location_type'].unique())

Valeurs uniques dans location_type : [0]

In [45]:
# --- stop_timezone en minuscules ---
stops_df["stop_timezone"] = stops_df["stop_timezone"].str.lower()

# --- wheelchair_boarding et location_type en entier ---
stops_df["wheelchair_boarding"] = stops_df["wheelchair_boarding"].fillna(0).astype(int)
stops_df["location_type"] = stops_df["location_type"].fillna(0).astype(int)

# Vérification rapide
print(stops_df[["stop_timezone", "wheelchair_boarding", "location_type"]].head())

   stop_timezone  wheelchair_boarding  location_type
0  europe/madrid                    0              0
1  europe/madrid                    0              0
2  europe/madrid                    0              0
3  europe/madrid                    0              0
4  europe/madrid                    0              0

In [46]:
stops_df.sample(10)

,stop_id,stop_code,stop_name,stop_lat,stop_lon,location_type,stop_timezone,source_folder,wheelchair_boarding
222615,mobiiti:quay:113024,11296B,peybois,44.938915,-0.633153,0,europe/madrid,Nouvelle-Aquitaine Mobilités,2
112534,pf43172000,NaN,c. major s/n (marquesina bàscula municipal),41.336808,1.176749,0,europe/madrid,Generalitat of Catalonia (Intercity bus),0
198806,mobiiti:stopplace:60806,NaN,etang de cieux,45.987339,1.049767,0,europe/madrid,Nouvelle-Aquitaine Mobilités,2
260657,sp30914,1034012,granja piroño,42.363572,-8.056043,0,europe/madrid,Xunta de Galicia Buses,0
217368,mobiiti:stopplace:77153,NaN,nouvelle du port,45.182793,0.705279,0,europe/madrid,Nouvelle-Aquitaine Mobilités,2
220910,mobiiti:stopplace:70759,NaN,benaben,45.297150,-0.927625,0,europe/madrid,Nouvelle-Aquitaine Mobilités,2
107933,pf08072090,NaN,sol ixent,41.418324,1.898071,0,europe/madrid,Generalitat of Catalonia (Intercity bus),0
91004,par_8_07716,7716,móstoles-austria,40.289005,-3.802690,0,europe/madrid,Consorcio Regional de Transportes de Madrid CR...,2
93055,par_8_18305,18305,encina-san nicasio,40.337048,-3.775604,0,europe/madrid,Consorcio Regional de Transportes de Madrid CR...,0
150297,de:08226:4252:30:west2,NaN,"wiesloch-walldorf, bf bstg west2",49.291111,8.663748,0,europe/madrid,NVBW - Nahverkehrsgesellschaft Baden-Württemb...,0

In [47]:
stops_df["stop_name"] = stops_df["stop_name"].str.replace(r"\s+", " ", regex=True).str.strip()

In [48]:
stops_df.sample(10)

,stop_id,stop_code,stop_name,stop_lat,stop_lon,location_type,stop_timezone,source_folder,wheelchair_boarding
209367,mobiiti:stopplace:59928,NaN,lr st aubin de ca-la mouline (2),44.680508,0.500080,0,europe/madrid,Nouvelle-Aquitaine Mobilités,2
110279,pf08175012,NaN,can vidal (a) mb0623,41.945616,1.880053,0,europe/madrid,Generalitat of Catalonia (Intercity bus),0
269042,sp40885,1042093,bermello,43.141673,-8.929243,0,europe/madrid,Xunta de Galicia Buses,0
112225,pf17216000,NaN,viladasens,42.095568,2.930095,0,europe/madrid,Generalitat of Catalonia (Intercity bus),0
109244,pf25217016,NaN,c/ del nord cantonada c/ enric de càrcer,41.651376,1.141219,0,europe/madrid,Generalitat of Catalonia (Intercity bus),0
78107,par_8_10652,10652,vda.yeguas-av.guijar,40.316635,-3.463995,0,europe/madrid,Consorcio Regional de Transportes de Madrid CR...,2
32303,gen_pf43166002,NaN,c. del morell,41.208813,1.205581,0,europe/madrid,Autoridad de Transporte Metropolitano del Area...,0
21517,bgs_3886,3886,institut moianès,41.806126,2.099659,0,europe/madrid,Autoridad de Transporte Metropolitano del Area...,0
200772,mobiiti:quay:83016,Tpofi2,pôle fiduciaire - centre de publipostage,44.613960,-1.120146,0,europe/madrid,Nouvelle-Aquitaine Mobilités,2
164471,de:08335:2916:0:1,NaN,stockach berlingerweg - siedlung,47.866392,9.024493,0,europe/madrid,NVBW - Nahverkehrsgesellschaft Baden-Württemb...,0

In [49]:
import os

# Dossier principal contenant les sous-dossiers
main_folder = "/content/drive/MyDrive/GTFS_CLEAN"  # mettre ton chemin exact

# Parcourir toutes les valeurs uniques de source_folder dans stops_df
for subfolder_name in stops_df["source_folder"].unique():
    subfolder_path = os.path.join(main_folder, subfolder_name)

    # Créer le dossier s'il n'existe pas
    if not os.path.exists(subfolder_path):
        os.makedirs(subfolder_path)

    # Sélectionner uniquement les lignes correspondant à ce sous-dossier
    df_subset = stops_df[stops_df["source_folder"] == subfolder_name].copy()

    # Supprimer la colonne source_folder
    if "source_folder" in df_subset.columns:
        df_subset.drop(columns=["source_folder"], inplace=True)

    # Définir le chemin du fichier
    output_file = os.path.join(subfolder_path, "stop_clean.txt")

    # Sauvegarder le dataframe filtré
    df_subset.to_csv(output_file, index=False, sep=",", encoding="utf-8")

    print(f"📥 Fichier créé : {output_file} ({len(df_subset)} lignes)")

📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/AISA (Bus Madrid-Aranda de Duero-Burgo de Osma)/stop_clean.txt (36 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/ALSA buses/stop_clean.txt (11470 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/AUCORSA (Autobuses de Córdoba S.A.)/stop_clean.txt (613 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/AUTNA SL/stop_clean.txt (9 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Alavabus/stop_clean.txt (678 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Alvarez Travelers Coaches/stop_clean.txt (65 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Ancebus/stop_clean.txt (26 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Auif Irunbus (Lurraldebus)/stop_clean.txt (72 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Autocares Baraza (Baraza Coaches)/stop_clean.txt (50 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Autocares Rías Baixas (Rías Baixas Coaches)/stop_clean.txt (2549 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Autocorb Coaches/stop_clean.txt (170 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Autoridad de Transporte Metropolitano del Area de Barcelona (ATM) Buses and trains in Catalonia (full version)/stop_clean.txt (28410 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Avanza Grupo (Ávila city bus)/stop_clean.txt (194 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Avanza Grupo (Huesca city bus)/stop_clean.txt (68 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Avanza Grupo (Mataró city bus)/stop_clean.txt (145 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Avanza Grupo (Segovia city bus)/stop_clean.txt (155 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Avanza Grupo (Soria city bus)/stop_clean.txt (81 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Avanza Grupo (VAC-124. Huesca-Lleida with branches)/stop_clean.txt (57 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Avanza Grupo (VAC-245. Huesca-Barcelona)/stop_clean.txt (7 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Àrea Metropolitana de Barcelona (AMB)/stop_clean.txt (4815 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Bermibusa/stop_clean.txt (20 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Bizkaibus/stop_clean.txt (2304 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/BlaBlaCar Bus/stop_clean.txt (346 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Catalonia Area de Barcelona/stop_clean.txt (24076 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/City Council of Las Palmas de Gran Canaria (city bus)/stop_clean.txt (848 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Collegamenti marittimi Grandi Navi Veloci/stop_clean.txt (36 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Collegamenti marittimi Grimaldi/stop_clean.txt (36 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Consorcio Regional de Transportes de Madrid CRTM Intercity Buses (Madrid Intercity Bus)/stop_clean.txt (8392 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Consorcio Regional de Transportes de Madrid CRTM Light Rail Network (Red de Metro Ligero)/stop_clean.txt (78 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Consorcio Regional de Transportes de Madrid CRTM Madrid City Bus (Autobus urbano de Madrid)/stop_clean.txt (8392 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Consorcio Regional de Transportes de Madrid Métro Ligero de Madrid/stop_clean.txt (78 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Consorcio Regional de Transportes de Madrid Réseau de navettes CRTM (Red de Cercanías)/stop_clean.txt (97 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Costa Coaches/stop_clean.txt (446 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Cots Alsina/stop_clean.txt (97 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Direxis Masats/stop_clean.txt (161 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Direxis TGO (Transportes Generales de Olesa)/stop_clean.txt (419 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/EMT Tarragona/stop_clean.txt (408 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/El Transbordador de Vizcaya/stop_clean.txt (2 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/El Transbordador de Vizcaya (Bizkaia Bridge Ferry)/stop_clean.txt (2 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Empresa Municipal de Transportes de Madrid (EMT Madrid)/stop_clean.txt (4917 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Empresa Municipal de Transportes de Valencia (EMT Valencia)/stop_clean.txt (1148 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Empresa Municipal de Transports Urbans de Palma de Mallorca/stop_clean.txt (873 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Erandio City Council (Erandio! Busa)/stop_clean.txt (55 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Etxebarri Town Hall/stop_clean.txt (24 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Euskotren/stop_clean.txt (798 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/FGV - Generalitat Valenciana Metro de Valencia/stop_clean.txt (144 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/FGV - Generalitat Valenciana Trains and trams in Alicante and the Costa Blanca/stop_clean.txt (70 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Ferry Fred. Olsen (Fred Olsen Express)/stop_clean.txt (13 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Funiculaire de Artxanda/stop_clean.txt (2 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Generalitat of Catalonia (Intercity bus)/stop_clean.txt (8715 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Gobierno de Cantabria (Bus en Cantabrie)/stop_clean.txt (973 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Granada City Council (Granada city bus)/stop_clean.txt (680 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Guaguas Municipales/stop_clean.txt (848 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Junta de Extremadura (Bus du gouvernement régional d’Estrémadure)/stop_clean.txt (520 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Kbus (Barakaldo urban)/stop_clean.txt (88 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/La Burundesa_SA/stop_clean.txt (158 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/La Coruña Tram Company SA/stop_clean.txt (535 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/La Regional Vallisoletana SA/stop_clean.txt (66 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/La Veloz SA (Buses from the Belchite countryside area to Zaragoza (C12))/stop_clean.txt (37 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Lázara Coaches/stop_clean.txt (1321 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Leioa City Council (Lejoan Busa)/stop_clean.txt (30 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Lurraldebus - Hernani Urban (bus urbain d’Hernani)/stop_clean.txt (27 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Lurraldebus Arrasate/stop_clean.txt (54 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Lurraldebus Eibar/stop_clean.txt (38 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Lurraldebus Ekialdebus/stop_clean.txt (229 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Lurraldebus Euskotren bus/stop_clean.txt (234 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Lurraldebus Goierrialdea/stop_clean.txt (201 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Lurraldebus Guipuzcoana (La Guipuzcoana)/stop_clean.txt (178 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Lurraldebus Lasarte/stop_clean.txt (38 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Lurraldebus Oiartzun (Xorrola)/stop_clean.txt (16 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Lurraldebus TBH (Interurban Tolosa Buruntzaldea)/stop_clean.txt (238 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Lurraldebus Tolosaldea/stop_clean.txt (234 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Lurraldebus Urbano de Errentería (Errenteria Urbanoa)/stop_clean.txt (82 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Lurraldebus Zarautz/stop_clean.txt (34 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Metro de Sevilla/stop_clean.txt (42 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/MetroValencia/stop_clean.txt (144 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Metropolitano de Tenerife (Metrotenerife)/stop_clean.txt (25 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Métro Bilbao/stop_clean.txt (191 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Métro de Madrid/stop_clean.txt (1050 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/NVBW - Nahverkehrsgesellschaft Baden-Württemberg mbH/stop_clean.txt (61509 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Nouvelle-Aquitaine Mobilités/stop_clean.txt (43189 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Oñati urbain (Oñatiko herribusa)/stop_clean.txt (32 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Ouigo/stop_clean.txt (16 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Palma City Council (Palma de Mallorca city bus)/stop_clean.txt (873 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Pinto City Council/stop_clean.txt (59 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Rafael Nadal Coaches/stop_clean.txt (3 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Réseau interurbain liO Occitanie/stop_clean.txt (12288 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Rodil/stop_clean.txt (81 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Sopela Town Hall/stop_clean.txt (18 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/TIB Transports de les Illes Balears - CTM Transport Consortium of Mallorcam (Public transport on the island of Mallorca)/stop_clean.txt (704 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/TIB Transports of the Balearic Islands - CIE Consell Insular d'Eivissa (Ibiza Island Bus)/stop_clean.txt (592 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/TIB Transports of the Balearic Islands - CIME Consell Insular de Menorca (Menorca Island Bus)/stop_clean.txt (196 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/TMESA/stop_clean.txt (350 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/TRAM Alicante/stop_clean.txt (70 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/TUS (Transportes Urbanos de Santander)/stop_clean.txt (460 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/TUSSAM (Seville bus and tram)/stop_clean.txt (1046 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Tolosa City Council (Urbano de Tolosa)/stop_clean.txt (26 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/TranspRober/stop_clean.txt (680 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Transports Municipals del Gironés SAU (TMG) Girona city bus/stop_clean.txt (250 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Transports Municipaux D’Egara (TMESA) Terrassa bus urbain/stop_clean.txt (350 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Vectalia Movilidad (bus de la ville de Cáceres)/stop_clean.txt (237 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Viagón Coaches/stop_clean.txt (62 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/Xunta de Galicia Buses/stop_clean.txt (26897 lignes)
📥 Fichier créé : /content/drive/MyDrive/GTFS_CLEAN/dBus (Donostiabus)/stop_clean.txt (535 lignes)

In [3]:
import os
import pandas as pd

# Dossier principal contenant les sous-dossiers
GTFS_CLEAN = "/content/drive/MyDrive/GTFS_CLEAN"  # mettre ton chemin exact

all_stop_times = []  # liste pour stocker tous les df stop_times.txt

# Parcourir les sous-dossiers
for subfolder in sorted(os.listdir(GTFS_CLEAN)):
    folder_path = os.path.join(GTFS_CLEAN, subfolder)

    # Vérifier que c'est bien un dossier
    if not os.path.isdir(folder_path):
        continue

    stop_times_path = os.path.join(folder_path, "stop_times.txt")

    # Vérifier que le fichier stop_times.txt existe
    if os.path.exists(stop_times_path):
        try:
            df = pd.read_csv(stop_times_path, encoding="utf-8", on_bad_lines="skip")

            # Ajouter la colonne pour savoir d'où vient la ligne
            df["source_folder"] = subfolder

            # Ajouter le dataframe à la liste
            all_stop_times.append(df)

            print(f"📥 stop_times.txt chargé depuis : {subfolder} ({len(df)} lignes)")
        except Exception as e:
            print(f"⚠️ Erreur lecture dans {subfolder}: {e}")
    else:
        print(f"❌ Aucun stop_times.txt dans : {subfolder}")

# Combiner tous les dataframes en un seul si nécessaire
if all_stop_times:
    stop_times_df = pd.concat(all_stop_times, ignore_index=True)
    print(f"\n✅ stop_times.txt combinés : {len(stop_times_df)} lignes au total")
else:
    print("\n❌ Aucun stop_times.txt trouvé dans tous les sous-dossiers")

📥 stop_times.txt chargé depuis : AISA (Bus Madrid-Aranda de Duero-Burgo de Osma) (340 lignes)
📥 stop_times.txt chargé depuis : ALSA buses (705664 lignes)
📥 stop_times.txt chargé depuis : AUCORSA (Autobuses de Córdoba S.A.) (128855 lignes)
📥 stop_times.txt chargé depuis : AUTNA SL (116 lignes)
📥 stop_times.txt chargé depuis : Alavabus (27904 lignes)
📥 stop_times.txt chargé depuis : Alvarez Travelers Coaches (142 lignes)
📥 stop_times.txt chargé depuis : Ancebus (52 lignes)
📥 stop_times.txt chargé depuis : Auif Irunbus (Lurraldebus) (2663 lignes)
📥 stop_times.txt chargé depuis : Autocares Baraza (Baraza Coaches) (778 lignes)
📥 stop_times.txt chargé depuis : Autocares Rías Baixas (Rías Baixas Coaches) (34312 lignes)
📥 stop_times.txt chargé depuis : Autocorb Coaches (8422 lignes)

/tmp/ipython-input-2156357455.py:22: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(stop_times_path, encoding="utf-8", on_bad_lines="skip")

📥 stop_times.txt chargé depuis : Autoridad de Transporte Metropolitano del Area de Barcelona (ATM) Buses and trains in Catalonia (full version) (4219428 lignes)
📥 stop_times.txt chargé depuis : Avanza Grupo (Ávila city bus) (22328 lignes)
📥 stop_times.txt chargé depuis : Avanza Grupo (Huesca city bus) (3916 lignes)
📥 stop_times.txt chargé depuis : Avanza Grupo (Mataró city bus) (33944 lignes)
📥 stop_times.txt chargé depuis : Avanza Grupo (Segovia city bus) (69828 lignes)
📥 stop_times.txt chargé depuis : Avanza Grupo (Soria city bus) (4387 lignes)
📥 stop_times.txt chargé depuis : Avanza Grupo (VAC-124. Huesca-Lleida with branches) (894 lignes)
📥 stop_times.txt chargé depuis : Avanza Grupo (VAC-245. Huesca-Barcelona) (342 lignes)
📥 stop_times.txt chargé depuis : Àrea Metropolitana de Barcelona (AMB) (980023 lignes)
📥 stop_times.txt chargé depuis : Bermibusa (630 lignes)
📥 stop_times.txt chargé depuis : Bizkaibus (604263 lignes)
📥 stop_times.txt chargé depuis : BlaBlaCar Bus (31610 lignes)

/tmp/ipython-input-2156357455.py:22: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(stop_times_path, encoding="utf-8", on_bad_lines="skip")

📥 stop_times.txt chargé depuis : Catalonia Area de Barcelona (3954736 lignes)
📥 stop_times.txt chargé depuis : City Council of Las Palmas de Gran Canaria (city bus) (155324 lignes)
📥 stop_times.txt chargé depuis : Collegamenti marittimi Grandi Navi Veloci (84 lignes)
📥 stop_times.txt chargé depuis : Collegamenti marittimi Grimaldi (60 lignes)
📥 stop_times.txt chargé depuis : Consorcio Regional de Transportes de Madrid CRTM Intercity Buses (Madrid Intercity Bus) (1255978 lignes)
📥 stop_times.txt chargé depuis : Consorcio Regional de Transportes de Madrid CRTM Light Rail Network (Red de Metro Ligero) (37336 lignes)
📥 stop_times.txt chargé depuis : Consorcio Regional de Transportes de Madrid CRTM Madrid City Bus (Autobus urbano de Madrid) (436842 lignes)
📥 stop_times.txt chargé depuis : Consorcio Regional de Transportes de Madrid Métro Ligero de Madrid (37336 lignes)
📥 stop_times.txt chargé depuis : Consorcio Regional de Transportes de Madrid Réseau de navettes CRTM (Red de Cercanías) (0 lignes)
📥 stop_times.txt chargé depuis : Costa Coaches (3847 lignes)
📥 stop_times.txt chargé depuis : Cots Alsina (5695 lignes)
📥 stop_times.txt chargé depuis : Direxis Masats (15156 lignes)
📥 stop_times.txt chargé depuis : Direxis TGO (Transportes Generales de Olesa) (10717 lignes)
📥 stop_times.txt chargé depuis : EMT Tarragona (51562 lignes)
📥 stop_times.txt chargé depuis : El Transbordador de Vizcaya (16 lignes)
📥 stop_times.txt chargé depuis : El Transbordador de Vizcaya (Bizkaia Bridge Ferry) (16 lignes)
📥 stop_times.txt chargé depuis : Empresa Municipal de Transportes de Madrid (EMT Madrid) (2262704 lignes)
📥 stop_times.txt chargé depuis : Empresa Municipal de Transportes de Valencia (EMT Valencia) (755942 lignes)
📥 stop_times.txt chargé depuis : Empresa Municipal de Transports Urbans de Palma de Mallorca (5431 lignes)
📥 stop_times.txt chargé depuis : Erandio City Council (Erandio! Busa) (1488 lignes)
📥 stop_times.txt chargé depuis : Etxebarri Town Hall (2919 lignes)
📥 stop_times.txt chargé depuis : Euskotren (105542 lignes)
📥 stop_times.txt chargé depuis : FGV - Generalitat Valenciana Metro de Valencia (236283 lignes)
📥 stop_times.txt chargé depuis : FGV - Generalitat Valenciana Trains and trams in Alicante and the Costa Blanca (24019 lignes)
📥 stop_times.txt chargé depuis : Ferry Fred. Olsen (Fred Olsen Express) (18201 lignes)
📥 stop_times.txt chargé depuis : Funiculaire de Artxanda (2486 lignes)
📥 stop_times.txt chargé depuis : Generalitat of Catalonia (Intercity bus) (416675 lignes)
📥 stop_times.txt chargé depuis : Gobierno de Cantabria (Bus en Cantabrie) (31550 lignes)
📥 stop_times.txt chargé depuis : Granada City Council (Granada city bus) (277313 lignes)
📥 stop_times.txt chargé depuis : Guaguas Municipales (155324 lignes)
📥 stop_times.txt chargé depuis : Junta de Extremadura (Bus du gouvernement régional d’Estrémadure) (4719 lignes)
📥 stop_times.txt chargé depuis : Kbus (Barakaldo urban) (6142 lignes)
📥 stop_times.txt chargé depuis : La Burundesa_SA (1460 lignes)
📥 stop_times.txt chargé depuis : La Coruña Tram Company SA (348165 lignes)
📥 stop_times.txt chargé depuis : La Regional Vallisoletana SA (4344 lignes)
📥 stop_times.txt chargé depuis : La Veloz SA (Buses from the Belchite countryside area to Zaragoza (C12)) (468 lignes)
📥 stop_times.txt chargé depuis : Lázara Coaches (11988 lignes)
📥 stop_times.txt chargé depuis : Leioa City Council (Lejoan Busa) (3564 lignes)
📥 stop_times.txt chargé depuis : Lurraldebus - Hernani Urban (bus urbain d’Hernani) (412 lignes)
📥 stop_times.txt chargé depuis : Lurraldebus Arrasate (2985 lignes)
📥 stop_times.txt chargé depuis : Lurraldebus Eibar (634 lignes)
📥 stop_times.txt chargé depuis : Lurraldebus Ekialdebus (149423 lignes)
📥 stop_times.txt chargé depuis : Lurraldebus Euskotren bus (45826 lignes)
📥 stop_times.txt chargé depuis : Lurraldebus Goierrialdea (20310 lignes)
📥 stop_times.txt chargé depuis : Lurraldebus Guipuzcoana (La Guipuzcoana) (26596 lignes)
📥 stop_times.txt chargé depuis : Lurraldebus Lasarte (1509 lignes)
📥 stop_times.txt chargé depuis : Lurraldebus Oiartzun (Xorrola) (722 lignes)
📥 stop_times.txt chargé depuis : Lurraldebus Pesa (0 lignes)
📥 stop_times.txt chargé depuis : Lurraldebus TBH (Interurban Tolosa Buruntzaldea) (105041 lignes)
📥 stop_times.txt chargé depuis : Lurraldebus Tolosaldea (9569 lignes)
📥 stop_times.txt chargé depuis : Lurraldebus Urbano de Errentería (Errenteria Urbanoa) (5307 lignes)
📥 stop_times.txt chargé depuis : Lurraldebus Zarautz (2765 lignes)
📥 stop_times.txt chargé depuis : Metro de Sevilla (1784 lignes)
📥 stop_times.txt chargé depuis : MetroValencia (236283 lignes)
📥 stop_times.txt chargé depuis : Metropolitano de Tenerife (Metrotenerife) (162 lignes)
📥 stop_times.txt chargé depuis : Métro Bilbao (150256 lignes)
📥 stop_times.txt chargé depuis : Métro de Madrid (2216 lignes)

/tmp/ipython-input-2156357455.py:22: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(stop_times_path, encoding="utf-8", on_bad_lines="skip")

📥 stop_times.txt chargé depuis : NVBW - Nahverkehrsgesellschaft Baden-Württemberg mbH (6145124 lignes)

/tmp/ipython-input-2156357455.py:22: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(stop_times_path, encoding="utf-8", on_bad_lines="skip")

📥 stop_times.txt chargé depuis : Nouvelle-Aquitaine Mobilités (3840484 lignes)
📥 stop_times.txt chargé depuis : Oñati urbain (Oñatiko herribusa) (922 lignes)
📥 stop_times.txt chargé depuis : Ouigo (181 lignes)
📥 stop_times.txt chargé depuis : Palma City Council (Palma de Mallorca city bus) (5431 lignes)
📥 stop_times.txt chargé depuis : Pinto City Council (895 lignes)
📥 stop_times.txt chargé depuis : Rafael Nadal Coaches (6 lignes)

/tmp/ipython-input-2156357455.py:22: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(stop_times_path, encoding="utf-8", on_bad_lines="skip")

📥 stop_times.txt chargé depuis : Réseau interurbain liO Occitanie (172366 lignes)
📥 stop_times.txt chargé depuis : Rodil (694 lignes)
📥 stop_times.txt chargé depuis : Sopela Town Hall (319 lignes)
📥 stop_times.txt chargé depuis : TIB Transports de les Illes Balears - CTM Transport Consortium of Mallorcam (Public transport on the island of Mallorca) (45551 lignes)
📥 stop_times.txt chargé depuis : TIB Transports of the Balearic Islands - CIE Consell Insular d'Eivissa (Ibiza Island Bus) (32374 lignes)
📥 stop_times.txt chargé depuis : TIB Transports of the Balearic Islands - CIME Consell Insular de Menorca (Menorca Island Bus) (9980 lignes)
📥 stop_times.txt chargé depuis : TMESA (121845 lignes)
📥 stop_times.txt chargé depuis : TRAM Alicante (57852 lignes)
📥 stop_times.txt chargé depuis : TUS (Transportes Urbanos de Santander) (118535 lignes)
📥 stop_times.txt chargé depuis : TUSSAM (Seville bus and tram) (526998 lignes)
📥 stop_times.txt chargé depuis : Tolosa City Council (Urbano de Tolosa) (915 lignes)
📥 stop_times.txt chargé depuis : TranspRober (277313 lignes)
📥 stop_times.txt chargé depuis : Transports Municipals del Gironés SAU (TMG) Girona city bus (64826 lignes)
📥 stop_times.txt chargé depuis : Transports Municipaux D’Egara (TMESA) Terrassa bus urbain (124067 lignes)
📥 stop_times.txt chargé depuis : Vectalia Movilidad (bus de la ville de Cáceres) (290088 lignes)
📥 stop_times.txt chargé depuis : Viagón Coaches (240 lignes)
📥 stop_times.txt chargé depuis : Xunta de Galicia Buses (3384398 lignes)
📥 stop_times.txt chargé depuis : dBus (Donostiabus) (426017 lignes)

/tmp/ipython-input-2156357455.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stop_times_df = pd.concat(all_stop_times, ignore_index=True)

✅ stop_times.txt combinés : 33931494 lignes au total

In [ ]:
required_cols = ["trip_id", "arrival_time", "departure_time", "stop_id", "stop_sequence"]

for col in required_cols:
    if col in stop_times_df.columns:
        null_count = stop_times_df[col].isna().sum()
        empty_count = (stop_times_df[col].astype(str).str.strip() == "").sum()
        total_missing = null_count + empty_count

        percent = (total_missing / len(stop_times_df)) * 100

        print(f"{col} : {total_missing} valeurs manquantes ({percent:.2f}%)")
    else:
        print(f"⚠️ Colonne manquante dans le DataFrame : {col}")

In [2]:
import os
import pandas as pd
from collections import defaultdict

GTFS_CLEAN = "/content/drive/MyDrive/GTFS_CLEAN"

def analyze_column(chunk, col):
    total = len(chunk)

    nan_count = chunk[col].isna().sum()
    empty_count = (chunk[col] == "").sum()
    spaces_count = chunk[col].str.isspace().sum()

    valid_series = chunk[col].dropna().astype(str)
    unique_vals = valid_series.unique()

    return nan_count, empty_count, spaces_count, total, unique_vals


print("🔍 Début de l'analyse des fichiers stop_times.txt...\n")

for subfolder in sorted(os.listdir(GTFS_CLEAN)):
    folder_path = os.path.join(GTFS_CLEAN, subfolder)
    stop_times_path = os.path.join(folder_path, "stop_times.txt")

    if not os.path.exists(stop_times_path):
        continue

    print(f"📁 Analyse du fichier : {subfolder}/stop_times.txt")

    # Dictionnaires cumulés pour les résultats
    col_stats = defaultdict(lambda: {"nan": 0, "empty": 0, "spaces": 0, "total": 0, "unique": set()})

    for chunk in pd.read_csv(stop_times_path, chunksize=500_000, dtype=str, on_bad_lines="skip"):

        for col in chunk.columns:

            nan_c, empty_c, spaces_c, total_c, unique_vals = analyze_column(chunk, col)

            col_stats[col]["nan"] += nan_c
            col_stats[col]["empty"] += empty_c
            col_stats[col]["spaces"] += spaces_c
            col_stats[col]["total"] += total_c

            # Ajouter uniques (attention : limité)
            if len(col_stats[col]["unique"]) < 50:
                col_stats[col]["unique"].update(unique_vals[:50])

    # Résultats Final
    for col, stats in col_stats.items():
        total = stats["total"]
        pct_nan = (stats["nan"] / total) * 100
        pct_empty = (stats["empty"] / total) * 100
        pct_spaces = (stats["spaces"] / total) * 100
        pct_problem = ((stats["nan"] + stats["empty"] + stats["spaces"]) / total) * 100

        print(f"\n🔎 Colonne : {col}")
        print(f"   - NaN           : {stats['nan']} ({pct_nan:.2f}%)")
        print(f"   - Vides ('')    : {stats['empty']} ({pct_empty:.2f}%)")
        print(f"   - Espaces       : {stats['spaces']} ({pct_spaces:.2f}%)")
        print(f"   - Total probs   : {pct_problem:.2f}%")
        print(f"   - Valeurs uniques (~max 50) : {len(stats['unique'])}")
        print(f"     ➤ Exemple : {list(stats['unique'])[:5]}")

    print("\n" + "-"*60 + "\n")

print("✅ Analyse terminée !")

🔍 Début de l'analyse des fichiers stop_times.txt...

📁 Analyse du fichier : AISA (Bus Madrid-Aranda de Duero-Burgo de Osma)/stop_times.txt

🔎 Colonne : trip_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 20
     ➤ Exemple : ['122', '153', '151', '142', '161']

🔎 Colonne : departure_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['13:13:00', '08:01:00', '09:02:00', '11:35:00', '07:50:00']

🔎 Colonne : arrival_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['13:13:00', '08:01:00', '09:02:00', '11:35:00', '07:50:00']

🔎 Colonne : stop_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 36
     ➤ Exemple : ['207', '56', '129', '150', '197']

🔎 Colonne : stop_sequence
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 27
     ➤ Exemple : ['3', '13', '21', '20', '18']

🔎 Colonne : pickup_type
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 1
     ➤ Exemple : ['0']

🔎 Colonne : drop_off_type
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 1
     ➤ Exemple : ['0']

🔎 Colonne : shape_dist_traveled
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['75', '56', '34', '20', '104']

------------------------------------------------------------

📁 Analyse du fichier : ALSA buses/stop_times.txt

🔎 Colonne : trip_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['000000420000959700000018', '000000420000959700000007', '000000420000958900003002', '000000420000959200000279', '000000420000959700000005']

🔎 Colonne : arrival_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['06:40:00', '06:56:00', '07:26:00', '07:32:00', '07:08:00']

🔎 Colonne : departure_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['06:40:00', '06:56:00', '07:26:00', '07:32:00', '07:08:00']

🔎 Colonne : stop_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['0030667300000001', '0031323300000001', '0030839700000001', '0032045400000001', '0031940800000001']

🔎 Colonne : stop_sequence
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['3', '13', '21', '34', '20']

🔎 Colonne : stop_headsign
   - NaN           : 705664 (100.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 100.00%
   - Valeurs uniques (~max 50) : 0
     ➤ Exemple : []

🔎 Colonne : pickup_type
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 3
     ➤ Exemple : ['2', '1', '0']

🔎 Colonne : drop_off_type
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 3
     ➤ Exemple : ['2', '1', '0']

🔎 Colonne : shape_dist_traveled
   - NaN           : 705664 (100.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 100.00%
   - Valeurs uniques (~max 50) : 0
     ➤ Exemple : []

------------------------------------------------------------

📁 Analyse du fichier : AUCORSA (Autobuses de Córdoba S.A.)/stop_times.txt

🔎 Colonne : trip_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['serv_01_02200200513', 'serv_01_02200200413', 'serv_01_02200201011', 'serv_01_02200200709', 'serv_01_02200200805']

🔎 Colonne : arrival_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['07:11:03', '07:10:55', '07:18:52', '07:05:52', '06:56:51']

🔎 Colonne : departure_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['07:11:03', '07:10:55', '07:18:52', '07:05:52', '06:56:51']

🔎 Colonne : stop_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['444', '56', '185', '445', '104']

🔎 Colonne : stop_sequence
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 43
     ➤ Exemple : ['3', '13', '21', '34', '20']

🔎 Colonne : stop_headsign
   - NaN           : 128855 (100.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 100.00%
   - Valeurs uniques (~max 50) : 0
     ➤ Exemple : []

🔎 Colonne : pickup_type
   - NaN           : 128855 (100.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 100.00%
   - Valeurs uniques (~max 50) : 0
     ➤ Exemple : []

🔎 Colonne : drop_off_type
   - NaN           : 128855 (100.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 100.00%
   - Valeurs uniques (~max 50) : 0
     ➤ Exemple : []

🔎 Colonne : shape_dist_traveled
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['4951', '3780', '2873', '6787', '5290']

------------------------------------------------------------

📁 Analyse du fichier : AUTNA SL/stop_times.txt

🔎 Colonne : trip_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 16
     ➤ Exemple : ['70-2-005-A-TS-12h15-OportoTerminalI', '70-2-002-AX2501-TU-12h15-OportoTerminalI', '70-2-003-AXFN-TU-15h15-OportoTerminalI', '70-1-005-A-TS-09h00-VigoEstacionInt', '70-1-001-AXFN-TU-04h30-VigoEstacionInt']

🔎 Colonne : arrival_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['19:45:00', '11:30:00', '15:15:00', '21:30:00', '19:55:00']

🔎 Colonne : departure_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['19:45:00', '11:30:00', '15:15:00', '21:30:00', '19:55:00']

🔎 Colonne : stop_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 9
     ➤ Exemple : ['35131', '35101', '35141', '35151', '35152']

🔎 Colonne : stop_sequence
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 8
     ➤ Exemple : ['2', '3', '6', '7', '1']

🔎 Colonne : stop_headsign
   - NaN           : 116 (100.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 100.00%
   - Valeurs uniques (~max 50) : 0
     ➤ Exemple : []

🔎 Colonne : pickup_type
   - NaN           : 116 (100.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 100.00%
   - Valeurs uniques (~max 50) : 0
     ➤ Exemple : []

🔎 Colonne : drop_off_type
   - NaN           : 116 (100.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 100.00%
   - Valeurs uniques (~max 50) : 0
     ➤ Exemple : []

🔎 Colonne : shape_dist_traveled
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 27
     ➤ Exemple : ['9138.93', '171864.09', '49537.98', '9137.48', '150035.22']

🔎 Colonne : timepoint
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 1
     ➤ Exemple : ['1']

------------------------------------------------------------

📁 Analyse du fichier : Alavabus/stop_times.txt

🔎 Colonne : trip_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['14122', '13483', '13314', '12960', '13486']

🔎 Colonne : arrival_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['20:13:00', '19:45:00', '20:24:00', '15:15:00', '20:23:00']

🔎 Colonne : departure_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['20:13:00', '19:45:00', '20:24:00', '15:15:00', '20:23:00']

🔎 Colonne : stop_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['444', '86', '207', '56', '461']

🔎 Colonne : stop_sequence
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 29
     ➤ Exemple : ['3', '13', '21', '20', '18']

🔎 Colonne : stop_headsign
   - NaN           : 27904 (100.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 100.00%
   - Valeurs uniques (~max 50) : 0
     ➤ Exemple : []

🔎 Colonne : pickup_type
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 3
     ➤ Exemple : ['2', '1', '0']

🔎 Colonne : drop_off_type
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 3
     ➤ Exemple : ['2', '1', '0']

🔎 Colonne : continuous_pickup
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 1
     ➤ Exemple : ['1']

🔎 Colonne : continuous_drop_off
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 1
     ➤ Exemple : ['1']

🔎 Colonne : shape_dist_traveled
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['29439', '39095', '28768', '24623', '2832']

🔎 Colonne : timepoint
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 2
     ➤ Exemple : ['1', '0']

------------------------------------------------------------

📁 Analyse du fichier : Alvarez Travelers Coaches/stop_times.txt

🔎 Colonne : trip_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 10
     ➤ Exemple : ['HIJUELAS_1', 'VACL-15_2', 'VACL-15_1', 'HIJUELAS_2', 'HIJUELAS_6']

🔎 Colonne : arrival_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['06:55:00', '07:26:00', '08:05:00', '08:32:00', '07:36:00']

🔎 Colonne : departure_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['06:55:00', '07:26:00', '08:05:00', '08:32:00', '07:36:00']

🔎 Colonne : stop_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['Castro de Sanabria', 'Codesal', 'Pías', 'Hedroso', 'Sotillo de Sanabria']

🔎 Colonne : stop_sequence
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 40
     ➤ Exemple : ['3', '13', '21', '34', '20']

------------------------------------------------------------

📁 Analyse du fichier : Ancebus/stop_times.txt

🔎 Colonne : trip_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 6
     ➤ Exemple : ['VACL060_2', 'VACL060_1', 'VACL018_1', 'VACL018_H1', 'VACL018_H2']

🔎 Colonne : arrival_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 47
     ➤ Exemple : ['06:40:00', '16:55:00', '06:55:00', '09:20:00', '07:20:00']

🔎 Colonne : departure_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 47
     ➤ Exemple : ['06:40:00', '16:55:00', '06:55:00', '09:20:00', '07:20:00']

🔎 Colonne : stop_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 26
     ➤ Exemple : ['ROBLEDO_HERMOSO', 'VILLAR_CIERVO', 'SAELICES', 'VILLAR_SAMANIEGO', 'SARDON']

🔎 Colonne : stop_sequence
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 13
     ➤ Exemple : ['2', '3', '13', '9', '6']

------------------------------------------------------------

📁 Analyse du fichier : Auif Irunbus (Lurraldebus)/stop_times.txt

🔎 Colonne : trip_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['1_101_FST_41400', '1_101_FST_30600', '3_301_FST_75600', '50_5001_FST_0', '2_201_FST_46800']

🔎 Colonne : arrival_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['15:15:00', '15:31:57', '01:01:35', '13:32:54', '01:18:16']

🔎 Colonne : departure_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['13:28:19', '15:38:08', '01:32:30', '13:41:07', '01:12:50']

🔎 Colonne : stop_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['1554', '1572', '1558', '1577', '1573']

🔎 Colonne : stop_sequence
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 24
     ➤ Exemple : ['3', '13', '21', '20', '18']

🔎 Colonne : stop_headsign
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['Dario De Regoyos, 19 (irun)', 'Irun - Elizatxo Hiribidea 11', 'Rotonda Arbes', 'Portu Plazatxoa', 'Aranzaran Plaza, 1']

🔎 Colonne : pickup_type
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 1
     ➤ Exemple : ['0']

🔎 Colonne : drop_off_type
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 1
     ➤ Exemple : ['0']

🔎 Colonne : timepoint
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 1
     ➤ Exemple : ['0']

------------------------------------------------------------

📁 Analyse du fichier : Autocares Baraza (Baraza Coaches)/stop_times.txt

🔎 Colonne : trip_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['Antas1145 - Vera', 'HOVERA1020 - LOS GALLARDOS', 'HOVERA1215 - LOS GALLARDOS', 'Antas1545 - Vera', 'HOVERA1715 - LOS GALLARDOS']

🔎 Colonne : arrival_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['08:32:00', '09:08:00', '09:06:00', '08:12:00', '08:18:00']

🔎 Colonne : departure_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['08:32:00', '09:08:00', '09:06:00', '08:12:00', '08:18:00']

🔎 Colonne : stop_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 46
     ➤ Exemple : ['P17', 'P30', 'P31', 'P37', 'P35']

🔎 Colonne : stop_sequence
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 24
     ➤ Exemple : ['3', '13', '21', '20', '18']

🔎 Colonne : stop_headsign
   - NaN           : 778 (100.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 100.00%
   - Valeurs uniques (~max 50) : 0
     ➤ Exemple : []

🔎 Colonne : pickup_type
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 1
     ➤ Exemple : ['0']

🔎 Colonne : drop_off_type
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 1
     ➤ Exemple : ['0']

🔎 Colonne : shape_dist_traveled
   - NaN           : 778 (100.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 100.00%
   - Valeurs uniques (~max 50) : 0
     ➤ Exemple : []

🔎 Colonne : timepoint
   - NaN           : 778 (100.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 100.00%
   - Valeurs uniques (~max 50) : 0
     ➤ Exemple : []

------------------------------------------------------------

📁 Analyse du fichier : Autocares Rías Baixas (Rías Baixas Coaches)/stop_times.txt

🔎 Colonne : trip_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%

/tmp/ipython-input-417830631.py:52: RuntimeWarning: invalid value encountered in scalar divide
  pct_nan = (stats["nan"] / total) * 100
/tmp/ipython-input-417830631.py:53: RuntimeWarning: invalid value encountered in scalar divide
  pct_empty = (stats["empty"] / total) * 100
/tmp/ipython-input-417830631.py:54: RuntimeWarning: invalid value encountered in scalar divide
  pct_spaces = (stats["spaces"] / total) * 100
/tmp/ipython-input-417830631.py:55: RuntimeWarning: invalid value encountered in scalar divide
  pct_problem = ((stats["nan"] + stats["empty"] + stats["spaces"]) / total) * 100

🔎 Colonne : trip_id
   - NaN           : 0 (nan%)
   - Vides ('')    : 0 (nan%)
   - Espaces       : 0 (nan%)
   - Total probs   : nan%
   - Valeurs uniques (~max 50) : 0
     ➤ Exemple : []

🔎 Colonne : arrival_time
   - NaN           : 0 (nan%)
   - Vides ('')    : 0 (nan%)
   - Espaces       : 0 (nan%)
   - Total probs   : nan%
   - Valeurs uniques (~max 50) : 0
     ➤ Exemple : []

🔎 Colonne : departure_time
   - NaN           : 0 (nan%)
   - Vides ('')    : 0 (nan%)
   - Espaces       : 0 (nan%)
   - Total probs   : nan%
   - Valeurs uniques (~max 50) : 0
     ➤ Exemple : []

🔎 Colonne : stop_id
   - NaN           : 0 (nan%)
   - Vides ('')    : 0 (nan%)
   - Espaces       : 0 (nan%)
   - Total probs   : nan%
   - Valeurs uniques (~max 50) : 0
     ➤ Exemple : []

🔎 Colonne : stop_sequence
   - NaN           : 0 (nan%)
   - Vides ('')    : 0 (nan%)
   - Espaces       : 0 (nan%)
   - Total probs   : nan%
   - Valeurs uniques (~max 50) : 0
     ➤ Exemple : []

🔎 Colonne : stop_headsign
   - NaN           : 0 (nan%)
   - Vides ('')    : 0 (nan%)
   - Espaces       : 0 (nan%)
   - Total probs   : nan%
   - Valeurs uniques (~max 50) : 0
     ➤ Exemple : []

🔎 Colonne : pickup_type
   - NaN           : 0 (nan%)
   - Vides ('')    : 0 (nan%)
   - Espaces       : 0 (nan%)
   - Total probs   : nan%
   - Valeurs uniques (~max 50) : 0
     ➤ Exemple : []

🔎 Colonne : drop_off_type
   - NaN           : 0 (nan%)
   - Vides ('')    : 0 (nan%)
   - Espaces       : 0 (nan%)
   - Total probs   : nan%
   - Valeurs uniques (~max 50) : 0
     ➤ Exemple : []

🔎 Colonne : shape_dist_traveled
   - NaN           : 0 (nan%)
   - Vides ('')    : 0 (nan%)
   - Espaces       : 0 (nan%)
   - Total probs   : nan%
   - Valeurs uniques (~max 50) : 0
     ➤ Exemple : []

------------------------------------------------------------

📁 Analyse du fichier : Costa Coaches/stop_times.txt

🔎 Colonne : trip_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['0095771075800815', '0095741078030830', '0095721076900802', '0095781075691330', '0095721076871425']

🔎 Colonne : arrival_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['16:34:00', '16:38:00', '16:55:00', '09:16:00', '09:20:00']

🔎 Colonne : departure_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['16:34:00', '16:38:00', '16:55:00', '09:16:00', '09:20:00']

🔎 Colonne : stop_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['4042047', '5041849', '2042010', '3000813', '5041939']

🔎 Colonne : stop_sequence
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['65', '207', '104', '88', '77']

🔎 Colonne : shape_dist_traveled
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['11500', '400', '4500', '2000', '11400']

🔎 Colonne : timepoint
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 1
     ➤ Exemple : ['1']

------------------------------------------------------------

📁 Analyse du fichier : Cots Alsina/stop_times.txt

🔎 Colonne : arrival_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['07:00:16', '07:10:16', '18:15:20', '08:10:03', '07:15:16']

🔎 Colonne : departure_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['07:00:16', '07:10:16', '18:15:20', '08:10:03', '07:15:16']

🔎 Colonne : stop_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['-207', '-211', '-214', '-134', '-133']

🔎 Colonne : stop_sequence
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 19
     ➤ Exemple : ['3', '13', '18', '1', '8']

🔎 Colonne : timepoint
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 2
     ➤ Exemple : ['2', '1']

🔎 Colonne : trip_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['60099212', '60092725', '60092886', '62552234', '60101150']

------------------------------------------------------------

📁 Analyse du fichier : Direxis Masats/stop_times.txt

🔎 Colonne : trip_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['LC1-109', 'LC1-107', 'LC1-118', 'LC1-101', 'LC1-205']

🔎 Colonne : arrival_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['07:26:00', '07:32:00', '10:06:00', '07:08:00', '07:36:00']

🔎 Colonne : departure_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['07:26:00', '07:32:00', '10:06:00', '07:08:00', '07:36:00']

🔎 Colonne : stop_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['087008', '087016', '087001', '087019', '087026']

🔎 Colonne : stop_sequence
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['230', '400', '175', '310', '20']

🔎 Colonne : stop_headsign
   - NaN           : 90 (0.59%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.59%
   - Valeurs uniques (~max 50) : 42
     ➤ Exemple : ['Rbla. St.Ferran  Estació  Hospital  Estació', 'Igualada', 'Zona Esportiva  Ctra. De Valls  Rbla. St.Ferran  Estació', 'Manresa', 'Av. Barcelona  Estació  Rbla. St. Ferran  Campus']

🔎 Colonne : pickup_type
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 3
     ➤ Exemple : ['2', '1', '0']

🔎 Colonne : drop_off_type
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 2
     ➤ Exemple : ['1', '0']

🔎 Colonne : timepoint
   - NaN           : 15156 (100.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 100.00%
   - Valeurs uniques (~max 50) : 0
     ➤ Exemple : []

------------------------------------------------------------

📁 Analyse du fichier : Direxis TGO (Transportes Generales de Olesa)/stop_times.txt

🔎 Colonne : trip_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['C6-A12', 'C6-T08', 'CS1-006', 'CS1-014', 'C6-A05']

🔎 Colonne : arrival_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['05:49:00', '06:15:00', '06:20:00', '04:49:00', '06:16:00']

🔎 Colonne : departure_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['05:49:00', '06:15:00', '06:20:00', '04:49:00', '06:16:00']

🔎 Colonne : stop_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['161015', '201253', '755048', '201390', '161003t']

🔎 Colonne : stop_sequence
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 41
     ➤ Exemple : ['65', '230', '310', '20', '360']

🔎 Colonne : stop_headsign
   - NaN           : 3290 (30.70%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 30.70%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['Olesa', 'Rellinars. Terrassa.', 'S.Cugat-Rubí-Terrassa', 'S.Cugat-Castellbisbal-El Papiol-Molins de Rei-S.Vicenç', 'El Papiol  Barcelona']

🔎 Colonne : pickup_type
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 3
     ➤ Exemple : ['2', '1', '0']

🔎 Colonne : drop_off_type
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 3
     ➤ Exemple : ['2', '1', '0']

🔎 Colonne : timepoint
   - NaN           : 10360 (96.67%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 96.67%
   - Valeurs uniques (~max 50) : 1
     ➤ Exemple : ['1']

------------------------------------------------------------

📁 Analyse du fichier : EMT Tarragona/stop_times.txt

🔎 Colonne : trip_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['03_1_0_9', '03_1_0_12', '03_0_0_21', '03_1_0_10', '03_0_0_4']

🔎 Colonne : arrival_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['05:22:00', '06:20:00', '06:21:00', '05:01:00', '06:04:00']

🔎 Colonne : departure_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['05:22:00', '06:20:00', '06:21:00', '05:01:00', '06:04:00']

🔎 Colonne : stop_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['25017', '25695', '25014', '25489', '25096']

🔎 Colonne : stop_sequence
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 39
     ➤ Exemple : ['3', '13', '21', '34', '20']

------------------------------------------------------------

📁 Analyse du fichier : El Transbordador de Vizcaya/stop_times.txt

🔎 Colonne : trip_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 8
     ➤ Exemple : ['403', '405', '408', '407', '404']

🔎 Colonne : arrival_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 8
     ➤ Exemple : ['00:00:00', '00:22:00', '04:38:00', '05:07:00', '00:08:00']

🔎 Colonne : departure_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 7
     ➤ Exemple : ['00:15:00', '04:55:00', '05:00:00', '00:00:00', '04:45:00']

🔎 Colonne : stop_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 2
     ➤ Exemple : ['Puente Bizkaia - Las Arenas', 'Puente Bizkaia - Portugalete']

🔎 Colonne : stop_sequence
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 2
     ➤ Exemple : ['2', '1']

🔎 Colonne : stop_headsign
   - NaN           : 16 (100.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 100.00%
   - Valeurs uniques (~max 50) : 0
     ➤ Exemple : []

🔎 Colonne : pickup_type
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 1
     ➤ Exemple : ['0']

🔎 Colonne : drop_off_type
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 1
     ➤ Exemple : ['0']

🔎 Colonne : shape_dist_traveled
   - NaN           : 8 (50.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 50.00%
   - Valeurs uniques (~max 50) : 1
     ➤ Exemple : ['0.16']

🔎 Colonne : timepoint
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 1
     ➤ Exemple : ['1']

------------------------------------------------------------

📁 Analyse du fichier : El Transbordador de Vizcaya (Bizkaia Bridge Ferry)/stop_times.txt

🔎 Colonne : trip_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 8
     ➤ Exemple : ['403', '405', '408', '407', '404']

🔎 Colonne : arrival_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 8
     ➤ Exemple : ['00:00:00', '00:22:00', '04:38:00', '05:07:00', '00:08:00']

🔎 Colonne : departure_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 7
     ➤ Exemple : ['00:15:00', '04:55:00', '05:00:00', '00:00:00', '04:45:00']

🔎 Colonne : stop_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 2
     ➤ Exemple : ['Puente Bizkaia - Las Arenas', 'Puente Bizkaia - Portugalete']

🔎 Colonne : stop_sequence
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 2
     ➤ Exemple : ['2', '1']

🔎 Colonne : stop_headsign
   - NaN           : 16 (100.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 100.00%
   - Valeurs uniques (~max 50) : 0
     ➤ Exemple : []

🔎 Colonne : pickup_type
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 1
     ➤ Exemple : ['0']

🔎 Colonne : drop_off_type
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 1
     ➤ Exemple : ['0']

🔎 Colonne : shape_dist_traveled
   - NaN           : 8 (50.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 50.00%
   - Valeurs uniques (~max 50) : 1
     ➤ Exemple : ['0.16']

🔎 Colonne : timepoint
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 1
     ➤ Exemple : ['1']

------------------------------------------------------------

📁 Analyse du fichier : Empresa Municipal de Transportes de Madrid (EMT Madrid)/stop_times.txt

🔎 Colonne : trip_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['FE00100217', 'FE0010014', 'FE0010025', 'FE0010033', 'FE00100211']

🔎 Colonne : arrival_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['07:04:18', '07:01:40', '07:27:05', '08:02:28', '07:16:05']

🔎 Colonne : departure_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['07:04:18', '07:01:40', '07:27:05', '08:02:28', '07:16:05']

🔎 Colonne : stop_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['733', '727', '169', '716', '735']

🔎 Colonne : stop_sequence
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 45
     ➤ Exemple : ['3', '13', '21', '34', '20']

🔎 Colonne : stop_headsign
   - NaN           : 2262704 (100.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 100.00%
   - Valeurs uniques (~max 50) : 0
     ➤ Exemple : []

🔎 Colonne : pickup_type
   - NaN           : 2262704 (100.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 100.00%
   - Valeurs uniques (~max 50) : 0
     ➤ Exemple : []

🔎 Colonne : drop_off_type
   - NaN           : 2262704 (100.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 100.00%
   - Valeurs uniques (~max 50) : 0
     ➤ Exemple : []

🔎 Colonne : shape_dist_traveled
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['169', '4174', '1952', '3200', '2275']

------------------------------------------------------------

📁 Analyse du fichier : Empresa Municipal de Transportes de Valencia (EMT Valencia)/stop_times.txt

🔎 Colonne : trip_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['4_1017_561_1585_2403_3_040', '4_1017_561_1585_2403_3_006', '4_1017_561_1585_2403_3_039', '4_1017_561_1585_2403_3_004', '4_1017_561_1585_2403_3_031']

🔎 Colonne : arrival_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['06:20:00', '05:58:35', '06:16:00', '06:25:02', '06:45:11']

🔎 Colonne : departure_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['06:20:00', '05:58:35', '06:16:00', '06:25:02', '06:45:11']

🔎 Colonne : stop_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['1617', '2206', '1919', '2122', '1981']

🔎 Colonne : stop_sequence
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['3', '13', '21', '34', '20']

🔎 Colonne : stop_headsign
   - NaN           : 755942 (100.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)

/tmp/ipython-input-417830631.py:52: RuntimeWarning: invalid value encountered in scalar divide
  pct_nan = (stats["nan"] / total) * 100
/tmp/ipython-input-417830631.py:53: RuntimeWarning: invalid value encountered in scalar divide
  pct_empty = (stats["empty"] / total) * 100
/tmp/ipython-input-417830631.py:54: RuntimeWarning: invalid value encountered in scalar divide
  pct_spaces = (stats["spaces"] / total) * 100
/tmp/ipython-input-417830631.py:55: RuntimeWarning: invalid value encountered in scalar divide
  pct_problem = ((stats["nan"] + stats["empty"] + stats["spaces"]) / total) * 100

🔎 Colonne : trip_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['5_502_15_58500', '8_802_27_72000', '4_403_25_30780', '2_204_26_37800', '3_304_25_64800']

🔎 Colonne : arrival_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['10:30:40', '19:20:03', '19:18:08', '10:54:57', '19:30:35']

🔎 Colonne : departure_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['10:46:45', '19:17:28', '19:20:08', '10:33:13', '19:33:08']

🔎 Colonne : stop_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['517', '733', '351', '385', '4146']

🔎 Colonne : stop_sequence
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 39
     ➤ Exemple : ['3', '13', '21', '34', '20']

🔎 Colonne : stop_headsign
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['Donostia - Begiristain Doktorea 218 - Onkologikoa', 'Usurbil - Kalezar Auzoa 9, Eskailerak', 'Lasarte-oria - Donostia Etorbidea - Sasoeta Oriamendi', 'Lasarte-oria - Kale Nagusia 40 - Zumaburu', 'Lasarte-oria - Kale Nagusia 70']

🔎 Colonne : pickup_type
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 1
     ➤ Exemple : ['0']

🔎 Colonne : drop_off_type
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 1
     ➤ Exemple : ['0']

🔎 Colonne : timepoint
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 1
     ➤ Exemple : ['0']

------------------------------------------------------------

📁 Analyse du fichier : Lurraldebus Tolosaldea/stop_times.txt

🔎 Colonne : trip_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['29_2901_D_36300', '26_2601_S_75300', '5_502_LV_66900', '2_209_D_74700', '3_306_LV_39600']

🔎 Colonne : arrival_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['12:47:11', '07:34:55', '16:54:44', '07:46:19', '07:50:00']

🔎 Colonne : departure_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['17:01:52', '07:39:44', '07:41:03', '17:03:32', '08:02:28']

🔎 Colonne : stop_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['3005', '2807', '3702', '1724', '3501']

🔎 Colonne : stop_sequence
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 23
     ➤ Exemple : ['3', '13', '21', '20', '18']

🔎 Colonne : stop_headsign
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['Ibarra - Euskal Herria Kalea 75, Ibarburu', 'Tolosa - Belate Pasealekua 1b', 'Belauntza - Hiriburu Gunea 6, Etxealai', 'Ibarra - Euskal Herria Kalea 55, Kultur Etxea', 'Tolosa - Iurramendi Pasealekua 10']

🔎 Colonne : pickup_type
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 1
     ➤ Exemple : ['0']

🔎 Colonne : drop_off_type
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 1
     ➤ Exemple : ['0']

🔎 Colonne : timepoint
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 1
     ➤ Exemple : ['0']

------------------------------------------------------------

📁 Analyse du fichier : Lurraldebus Urbano de Errentería (Errenteria Urbanoa)/stop_times.txt

🔎 Colonne : trip_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['22_2201_1_58500', '33_3301_1_51000', '22_2202_2_36300', '11_1101_3_51000', '11_1101_2_63000']

🔎 Colonne : arrival_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['10:10:06', '18:46:11', '10:13:40', '18:40:45', '18:49:21']

🔎 Colonne : departure_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['14:46:00', '18:49:52', '10:23:37', '10:19:58', '14:45:05']

🔎 Colonne : stop_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['5718', '5740', '5759', '5733', '5707']

🔎 Colonne : stop_sequence
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 32
     ➤ Exemple : ['3', '13', '21', '20', '18']

🔎 Colonne : stop_headsign
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['Alaberga 103', 'Galtzaraborda 49', 'Alaberga 40', 'Zumardia', 'Anbulategia']

🔎 Colonne : pickup_type
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 1
     ➤ Exemple : ['0']

🔎 Colonne : drop_off_type
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 1
     ➤ Exemple : ['0']

🔎 Colonne : timepoint
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 1
     ➤ Exemple : ['0']

------------------------------------------------------------

📁 Analyse du fichier : Lurraldebus Zarautz/stop_times.txt

🔎 Colonne : trip_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['5_502_1_58500', '23_231_25_74700', '5_501_25_54000', '1_103_1_34200', '3_301_5_53400']

🔎 Colonne : arrival_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['21:12:37', '21:19:58', '07:32:23', '07:17:19', '21:20:59']

🔎 Colonne : departure_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['07:41:20', '07:21:48', '21:23:07', '07:18:16', '16:01:14']

🔎 Colonne : stop_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 34
     ➤ Exemple : ['5855', '75', '422', '4694', '678']

🔎 Colonne : stop_sequence
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 21
     ➤ Exemple : ['3', '13', '21', '20', '18']

🔎 Colonne : stop_headsign
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 34
     ➤ Exemple : ['Eguneko Zentroa', 'Nafarroa Kalea- Sanzenea', 'La Salle Ikastetxea', 'Anbulategia', 'Nafarroa Kalea-pilartxo-enea']

🔎 Colonne : pickup_type
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 1
     ➤ Exemple : ['0']

🔎 Colonne : drop_off_type
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 1
     ➤ Exemple : ['0']

🔎 Colonne : timepoint
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 1
     ➤ Exemple : ['0']

------------------------------------------------------------

📁 Analyse du fichier : Metro de Sevilla/stop_times.txt

🔎 Colonne : trip_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['CE-PO-VIE-INV1-2024', 'CE-PO-VIE-INV2-2024', 'CE-OQ-SAB-INV1-2024', 'CE-OQ-LAB-INV1-2025', 'CE-PO-LAB-INV1-2024']

🔎 Colonne : arrival_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['6:55:45', '7:03:07', '7:00:26', '6:41:13', '6:52:18']

🔎 Colonne : departure_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['6:55:45', '7:03:07', '7:00:26', '6:41:13', '6:52:18']

🔎 Colonne : stop_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 21
     ➤ Exemple : ['L1-9', 'L1-17', 'L1-11', 'L1-21', 'L1-3']

🔎 Colonne : stop_sequence
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 21
     ➤ Exemple : ['3', '13', '21', '20', '18']

🔎 Colonne : stop_headsign
   - NaN           : 1784 (100.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 100.00%
   - Valeurs uniques (~max 50) : 0
     ➤ Exemple : []

🔎 Colonne : pickup_type
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 1
     ➤ Exemple : ['0']

🔎 Colonne : drop_off_type
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 1
     ➤ Exemple : ['0']

🔎 Colonne : shape_dist_traveled
   - NaN           : 1784 (100.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 100.00%
   - Valeurs uniques (~max 50) : 0
     ➤ Exemple : []

------------------------------------------------------------

📁 Analyse du fichier : MetroValencia/stop_times.txt

🔎 Colonne : trip_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['4811118', '4811140', '4811153', '4811129', '4811157']

🔎 Colonne : arrival_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['06:55:00', '08:02:00', '07:36:00', '07:20:00', '06:34:00']

🔎 Colonne : departure_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['06:55:00', '08:02:00', '07:36:00', '07:20:00', '06:34:00']

🔎 Colonne : stop_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['3', '13', '21', '34', '20']

🔎 Colonne : stop_sequence
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 40
     ➤ Exemple : ['3', '13', '21', '34', '20']

🔎 Colonne : timepoint
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 1
     ➤ Exemple : ['1']

------------------------------------------------------------

📁 Analyse du fichier : Metropolitano de Tenerife (Metrotenerife)/stop_times.txt

🔎 Colonne : trip_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 12
     ➤ Exemple : ['TLDO', 'TLSA', 'IT', 'ITDO', 'LTSA']

🔎 Colonne : arrival_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['6:11:00', '6:29:00', '6:14:00', '0:17:00', '0:02:00']

🔎 Colonne : departure_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['6:11:00', '6:29:00', '6:14:00', '0:17:00', '0:02:00']

🔎 Colonne : stop_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 25
     ➤ Exemple : ['13', '21', '02', '20', '18']

🔎 Colonne : stop_sequence
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 21
     ➤ Exemple : ['3', '13', '21', '20', '18']

------------------------------------------------------------

📁 Analyse du fichier : Métro Bilbao/stop_times.txt

🔎 Colonne : trip_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['689543', '689649', '689332', '689557', '689328']

🔎 Colonne : stop_sequence
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 31
     ➤ Exemple : ['3', '13', '21', '20', '1']

🔎 Colonne : arrival_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['09:06:23', '09:22:56', '09:32:14', '09:03:47', '13:23:26']

🔎 Colonne : departure_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['10:13:50', '09:23:14', '13:09:20', '10:11:17', '09:05:32']

🔎 Colonne : stop_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 42
     ➤ Exemple : ['11.0', '37.0', '36.0', '23.0', '42.0']

🔎 Colonne : pickup_type
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 1
     ➤ Exemple : ['0']

------------------------------------------------------------

📁 Analyse du fichier : Métro de Madrid/stop_times.txt

🔎 Colonne : trip_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['4_I13-004_2023I13_1_1_4__4___', '4_I12-072_2023I12_1_1_4__7_B__', '4_I12-071_2023I12_2_1_4__7_A__', '4_I15-071_2023I15_1_1_4__7_A__', '4_I12-001_2023I12_1_1_4__1___']

🔎 Colonne : arrival_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['01:05:17', '01:26:40', '01:15:40', '01:32:13', '01:36:43']

🔎 Colonne : departure_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['01:05:17', '01:26:40', '01:15:40', '01:32:13', '01:36:43']

🔎 Colonne : stop_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['par_4_4', 'par_4_14', 'par_4_21', 'par_4_262', 'par_4_6']

🔎 Colonne : stop_sequence
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 33
     ➤ Exemple : ['3', '13', '21', '20', '18']

🔎 Colonne : stop_headsign
   - NaN           : 2216 (100.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 100.00%
   - Valeurs uniques (~max 50) : 0
     ➤ Exemple : []

🔎 Colonne : pickup_type
   - NaN           : 2216 (100.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 100.00%
   - Valeurs uniques (~max 50) : 0
     ➤ Exemple : []

🔎 Colonne : drop_off_type
   - NaN           : 2216 (100.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 100.00%
   - Valeurs uniques (~max 50) : 0
     ➤ Exemple : []

🔎 Colonne : shape_dist_traveled
   - NaN           : 2216 (100.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 100.00%
   - Valeurs uniques (~max 50) : 0
     ➤ Exemple : []

------------------------------------------------------------

📁 Analyse du fichier : NVBW - Nahverkehrsgesellschaft Baden-Württemberg mbH/stop_times.txt

🔎 Colonne : trip_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['ovf-1-5523-1-1-3-R-2-Special-7-4', 'ovf-1-5523-1-1-8-R-4-Special-11-13', 'ovf-1-5523-1-1-17-H-2-Special#5-9-46', 'ovf-1-5523-1-1-3-R-2-Special-5-5', 'ovf-1-5523-1-1-11-R-7-Special#7-20-28']

🔎 Colonne : arrival_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['10:57:00', '06:55:00', '12:55:00', '07:36:00', '05:38:00']

🔎 Colonne : departure_time
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['10:57:00', '06:55:00', '12:55:00', '07:36:00', '05:38:00']

🔎 Colonne : stop_id
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['de:09676:1258:0:2', 'de:09663:319:10:12', 'de:08128:13593:0:RiS', 'de:09676:2123:0:2', 'de:09676:1878:0:2']

🔎 Colonne : stop_sequence
   - NaN           : 0 (0.00%)
   - Vides ('')    : 0 (0.00%)
   - Espaces       : 0 (0.00%)
   - Total probs   : 0.00%
   - Valeurs uniques (~max 50) : 50
     ➤ Exemple : ['3', '13', '21', '34', '20']

🔎 Colonne : stop_headsign