In [2]:
import os

folder_path = r"C:\Users\hp\Documents\OSM_SP"
files = os.listdir(folder_path)
print(files[:10])

['AISA__Bus_MadridAranda_de_DueroBurgo_de_Osma_.osm.pbf', 'Alavabus.osm.pbf', 'Alvarez_Travelers_Coaches.osm.pbf', 'Ancebus.osm.pbf', 'Area_Metropolitana_de_Barcelona__AMB_.osm.pbf', 'AUCORSA__Autobuses_de_Cordoba_SA_.osm.pbf', 'Auif_Irunbus__Lurraldebus_.osm.pbf', 'AUTNA_SL.osm.pbf', 'Autocares_Baraza__Baraza_Coaches_.osm.pbf', 'Autocares_Rias_Baixas__Rias_Baixas_Coaches_.osm.pbf']

In [3]:
!pip install --upgrade pyrosm

Requirement already satisfied: pyrosm in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (0.6.2)
Requirement already satisfied: python-rapidjson in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pyrosm) (1.22)
Requirement already satisfied: setuptools>=18.0 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pyrosm) (80.0.1)
Requirement already satisfied: geopandas>=0.12.0 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pyrosm) (1.1.1)
Requirement already satisfied: shapely>=2.0.1 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pyrosm) (2.1.2)
Requirement already satisfied: cykhash in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pyrosm) (2.0.1)
Requirement already satisfied: pyrobuf in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pyrosm) (0.9.3)
Requirement already satisfied: numpy>=1.24 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from geopandas>=0.12.0->pyrosm) (1.24.3)
Requirement already satisfied: pyogrio>=0.7.2 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from geopandas>=0.12.0->pyrosm) (0.11.1)
Requirement already satisfied: packaging in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from geopandas>=0.12.0->pyrosm) (23.2)
Requirement already satisfied: pandas>=2.0.0 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from geopandas>=0.12.0->pyrosm) (2.0.3)
Requirement already satisfied: pyproj>=3.5.0 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from geopandas>=0.12.0->pyrosm) (3.7.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas>=2.0.0->geopandas>=0.12.0->pyrosm) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas>=2.0.0->geopandas>=0.12.0->pyrosm) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas>=2.0.0->geopandas>=0.12.0->pyrosm) (2025.2)
Requirement already satisfied: certifi in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pyogrio>=0.7.2->geopandas>=0.12.0->pyrosm) (2025.1.31)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->geopandas>=0.12.0->pyrosm) (1.17.0)
Requirement already satisfied: jinja2>=2.8 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pyrobuf->pyrosm) (3.1.6)
Requirement already satisfied: cython>=0.23 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pyrobuf->pyrosm) (3.2.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from jinja2>=2.8->pyrobuf->pyrosm) (3.0.2)

[notice] A new release of pip is available: 25.1 -> 25.3
[notice] To update, run: C:\Users\hp\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [4]:
!pip show pyrosm

Name: pyrosm
Version: 0.6.2
Summary: A Python tool to parse OSM data from Protobuf format into GeoDataFrame.
Home-page: https://pyrosm.readthedocs.io/
Author: Henrikki Tenkanen
Author-email: henrikki.tenkanen@aalto.fi
License: MIT
Location: C:\Users\hp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages
Requires: cykhash, geopandas, pyrobuf, python-rapidjson, setuptools, shapely
Required-by:

In [3]:
pip install --upgrade pyrosm

Requirement already satisfied: pyrosm in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (0.6.2)
Requirement already satisfied: python-rapidjson in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pyrosm) (1.22)
Requirement already satisfied: setuptools>=18.0 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pyrosm) (80.0.1)
Requirement already satisfied: geopandas>=0.12.0 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pyrosm) (1.1.1)
Requirement already satisfied: shapely>=2.0.1 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pyrosm) (2.1.2)
Requirement already satisfied: cykhash in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pyrosm) (2.0.1)
Requirement already satisfied: pyrobuf in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pyrosm) (0.9.3)
Requirement already satisfied: numpy>=1.24 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from geopandas>=0.12.0->pyrosm) (1.24.3)
Requirement already satisfied: pyogrio>=0.7.2 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from geopandas>=0.12.0->pyrosm) (0.11.1)
Requirement already satisfied: packaging in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from geopandas>=0.12.0->pyrosm) (23.2)
Requirement already satisfied: pandas>=2.0.0 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from geopandas>=0.12.0->pyrosm) (2.0.3)
Requirement already satisfied: pyproj>=3.5.0 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from geopandas>=0.12.0->pyrosm) (3.7.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas>=2.0.0->geopandas>=0.12.0->pyrosm) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas>=2.0.0->geopandas>=0.12.0->pyrosm) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas>=2.0.0->geopandas>=0.12.0->pyrosm) (2025.2)
Requirement already satisfied: certifi in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pyogrio>=0.7.2->geopandas>=0.12.0->pyrosm) (2025.1.31)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->geopandas>=0.12.0->pyrosm) (1.17.0)
Requirement already satisfied: jinja2>=2.8 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pyrobuf->pyrosm) (3.1.6)
Requirement already satisfied: cython>=0.23 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pyrobuf->pyrosm) (3.2.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from jinja2>=2.8->pyrobuf->pyrosm) (3.0.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1 -> 25.3
[notice] To update, run: C:\Users\hp\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [ ]:
import os
from pyrosm import OSM
import pandas as pd

folder_path = r"C:\Users\hp\Documents\OSM_SP"

# Lister les fichiers .osm.pbf
files = [f for f in os.listdir(folder_path) if f.endswith(".osm.pbf")]
print(f"Nombre de fichiers trouvés : {len(files)}")
print("Exemples :", files[:10])

def inspect_osm(file_path, n=5):
    print(f"\n🔹 Lecture du fichier : {os.path.basename(file_path)}")
    osm = OSM(file_path)
    
    # Extraire les routes
    try:
        roads = osm.get_network(network_type="all")  # <-- méthode actuelle
        print(f"Nombre de routes trouvées : {len(roads)}")
        print(f"Aperçu des {n} premières lignes :")
        display(roads.head(n))
    except Exception as e:
        print("Erreur lors de l'extraction des routes :", e)
    
    # Extraire les points
    try:
        points = osm.get_pois()  # <-- points d'intérêt
        print(f"Nombre de POIs trouvés : {len(points)}")
        display(points.head(n))
    except Exception as e:
        print("Erreur lors de l'extraction des POIs :", e)

# Tester sur les 2-3 premiers fichiers
for file in files[:3]:
    inspect_osm(os.path.join(folder_path, file))

Nombre de fichiers trouvés : 105
Exemples : ['AISA__Bus_MadridAranda_de_DueroBurgo_de_Osma_.osm.pbf', 'Alavabus.osm.pbf', 'ALSA_buses.osm.pbf', 'Alvarez_Travelers_Coaches.osm.pbf', 'Ancebus.osm.pbf', 'Area_Metropolitana_de_Barcelona__AMB_.osm.pbf', 'AUCORSA__Autobuses_de_Cordoba_SA_.osm.pbf', 'Auif_Irunbus__Lurraldebus_.osm.pbf', 'AUTNA_SL.osm.pbf', 'Autocares_Baraza__Baraza_Coaches_.osm.pbf']

🔹 Lecture du fichier : AISA__Bus_MadridAranda_de_DueroBurgo_de_Osma_.osm.pbf
Nombre de routes trouvées : 130624
Aperçu des 5 premières lignes :

,access,area,bicycle,bridge,busway,cycleway,est_width,foot,footway,highway,...,tunnel,turn,width,id,geometry,length,timestamp,version,tags,osm_type
0,None,None,None,None,None,None,None,None,None,motorway,...,None,None,None,4049535,"MULTILINESTRING ((-3.67011 40.46894, -3.66969 ...",1211.0,1667338774,20,"{""visible"":false,""ref:colour"":""blue"",""source:n...",way
1,None,None,None,None,None,None,None,None,None,tertiary,...,None,None,None,4049543,"MULTILINESTRING ((-3.67883 40.44133, -3.67903 ...",148.0,1755553528,46,"{""visible"":false,""cycleway:both"":""no"",""destina...",way
2,None,None,None,None,None,None,None,None,None,motorway_link,...,None,None,None,4049564,"MULTILINESTRING ((-3.64505 40.48025, -3.64465 ...",91.0,1748255770,14,"{""visible"":false,""destination"":""Zaragoza;c. Gr...",way
3,None,None,None,None,None,None,None,None,None,motorway_link,...,None,None,None,4066695,"MULTILINESTRING ((-3.62375 40.46244, -3.62367 ...",310.0,1748256077,14,"{""visible"":false}",way
4,None,None,None,None,None,None,None,None,None,motorway_link,...,None,None,None,4066696,"MULTILINESTRING ((-3.61763 40.45853, -3.61774 ...",325.0,1732181261,13,"{""visible"":false,""lane_markings"":""no""}",way

Nombre de POIs trouvés : 33995

,version,tags,lat,visible,lon,id,timestamp,changeset,addr:city,addr:full,...,information,museum,tourism,geometry,osm_type,landuse,taxi,water,caravan_site,guest_house
0,4,None,40.463142,False,-3.636102,25931627,1610896759,0.0,None,None,...,None,None,None,POINT (-3.6361 40.46314),node,NaN,NaN,NaN,NaN,NaN
1,3,None,40.469807,False,-3.641920,25933508,1443348906,0.0,None,None,...,None,None,None,POINT (-3.64192 40.46981),node,NaN,NaN,NaN,NaN,NaN
2,3,None,40.469151,False,-3.641935,25933511,1443348906,0.0,None,None,...,None,None,None,POINT (-3.64194 40.46915),node,NaN,NaN,NaN,NaN,NaN
3,5,"{""access"":""private""}",40.477695,False,-3.708917,26202113,1703760533,0.0,None,None,...,None,None,None,POINT (-3.70892 40.4777),node,NaN,NaN,NaN,NaN,NaN
4,3,"{""access"":""private""}",40.477585,False,-3.707132,26202334,1531327158,0.0,None,None,...,None,None,None,POINT (-3.70713 40.47758),node,NaN,NaN,NaN,NaN,NaN

🔹 Lecture du fichier : Alavabus.osm.pbf

In [ ]:
import os
from pyrosm import OSM

# Dossier où se trouvent tes fichiers
folder_path = r"C:\Users\hp\Documents\OSM_SP"
files = os.listdir(folder_path)

# Choisir un fichier exemple
file_path = os.path.join(folder_path, files[0])
osm = OSM(file_path)

# Extraire les routes
roads = osm.get_network(network_type="all")

# Extraire les POIs
pois = osm.get_pois()

# Afficher toutes les colonnes disponibles
print("Colonnes des routes :")
print(list(roads.columns))

print("\nColonnes des POIs :")
print(list(pois.columns))

Colonnes des routes :
['access', 'area', 'bicycle', 'bridge', 'busway', 'cycleway', 'est_width', 'foot', 'footway', 'highway', 'int_ref', 'junction', 'lanes', 'lit', 'maxspeed', 'motorcar', 'motorroad', 'motor_vehicle', 'name', 'oneway', 'overtaking', 'passing_places', 'psv', 'ref', 'service', 'segregated', 'sidewalk', 'smoothness', 'surface', 'tracktype', 'tunnel', 'turn', 'width', 'id', 'timestamp', 'version', 'tags', 'osm_type', 'geometry', 'length']

Colonnes des POIs :
['changeset', 'timestamp', 'visible', 'id', 'tags', 'lon', 'lat', 'version', 'addr:city', 'addr:full', 'addr:housenumber', 'addr:housename', 'addr:postcode', 'addr:place', 'addr:street', 'email', 'name', 'opening_hours', 'operator', 'phone', 'ref', 'url', 'website', 'amenity', 'atm', 'bicycle_parking', 'bicycle_rental', 'bar', 'building', 'building:levels', 'drinking_water', 'fast_food', 'fountain', 'gambling', 'internet_access', 'office', 'parking', 'restaurant', 'school', 'social_facility', 'source', 'start_date', 'wikipedia', 'bicycle', 'books', 'butcher', 'clothes', 'craft', 'fireplace', 'furniture', 'hairdresser', 'kitchen', 'massage', 'medical_supply', 'motorcycle', 'organic', 'outdoor', 'pastry', 'religion', 'second_hand', 'shoes', 'shop', 'attraction', 'information', 'museum', 'tourism', 'geometry', 'osm_type', 'landuse', 'taxi', 'water', 'caravan_site', 'guest_house']

In [ ]:
import os
import pandas as pd
from pyrosm import OSM

# 📁 Dossier contenant les fichiers PBF
FOLDER_PATH = r"C:\Users\hp\Documents\OSM_SP"

# ✅ Colonnes attendues
selected_columns = [
    "id", "highway", "junction", "lanes", "maxspeed", "oneway",
    "busway", "psv", "motorcar", "access", "width", "smoothness",
    "name", "geometry", "length"
]

results = []

files = [f for f in os.listdir(FOLDER_PATH) if f.endswith(".osm.pbf")]

print(f"📂 Nombre total de fichiers : {len(files)}\n")

for file in files:
    file_path = os.path.join(FOLDER_PATH, file)
    print(f"🔍 Analyse : {file}")

    try:
        osm = OSM(file_path)
        roads = osm.get_network(network_type="driving")

        if roads is None or roads.empty:
            results.append({
                "file": file,
                "status": "❌ Aucun réseau routier",
                "missing_columns": selected_columns
            })
            print("   ❌ Aucun réseau trouvé\n")
            continue

        existing_cols = roads.columns.tolist()
        missing_cols = [c for c in selected_columns if c not in existing_cols]

        results.append({
            "file": file,
            "status": "✅ OK" if not missing_cols else "⚠️ Colonnes manquantes",
            "missing_columns": missing_cols
        })

        if missing_cols:
            print(f"   ⚠️ Colonnes manquantes : {missing_cols}\n")
        else:
            print("   ✅ Toutes les colonnes présentes\n")

    except Exception as e:
        results.append({
            "file": file,
            "status": "❌ Erreur de lecture",
            "missing_columns": selected_columns
        })
        print(f"   ❌ Erreur : {e}\n")

# 📊 Résumé global
df_results = pd.DataFrame(results)

print("\n📊 RÉSUMÉ GLOBAL")
print(df_results["status"].value_counts())

df_results

📂 Nombre total de fichiers : 105

🔍 Analyse : AISA__Bus_MadridAranda_de_DueroBurgo_de_Osma_.osm.pbf
   ✅ Toutes les colonnes présentes

🔍 Analyse : Alavabus.osm.pbf
   ✅ Toutes les colonnes présentes

🔍 Analyse : ALSA_buses.osm.pbf
   ❌ Erreur : Unable to allocate output buffer.

🔍 Analyse : Alvarez_Travelers_Coaches.osm.pbf
   ⚠️ Colonnes manquantes : ['busway']

🔍 Analyse : Ancebus.osm.pbf
   ⚠️ Colonnes manquantes : ['busway']

🔍 Analyse : Area_Metropolitana_de_Barcelona__AMB_.osm.pbf
   ✅ Toutes les colonnes présentes

🔍 Analyse : AUCORSA__Autobuses_de_Cordoba_SA_.osm.pbf
   ⚠️ Colonnes manquantes : ['busway']

🔍 Analyse : Auif_Irunbus__Lurraldebus_.osm.pbf
   ⚠️ Colonnes manquantes : ['busway', 'motorcar']

🔍 Analyse : AUTNA_SL.osm.pbf
   ✅ Toutes les colonnes présentes

🔍 Analyse : Autocares_Baraza__Baraza_Coaches_.osm.pbf
   ⚠️ Colonnes manquantes : ['busway', 'psv']

🔍 Analyse : Autocares_Rias_Baixas__Rias_Baixas_Coaches_.osm.pbf
   ✅ Toutes les colonnes présentes

🔍 Analyse : Autocorb_Coaches.osm.pbf
   ✅ Toutes les colonnes présentes

🔍 Analyse : Autoridad_de_Transporte_Metropolitano_del_Area_de_Barcelona__ATM__Buses_and_trains_in_Catalonia__full_version_.osm.pbf
   ❌ Erreur : Unable to allocate 31.2 KiB for an array with shape (8000,) and data type int32

🔍 Analyse : Avanza_Grupo__Avila_city_bus_.osm.pbf
   ⚠️ Colonnes manquantes : ['busway', 'psv', 'motorcar', 'smoothness']

🔍 Analyse : Avanza_Grupo__Huesca_city_bus_.osm.pbf
   ⚠️ Colonnes manquantes : ['busway', 'motorcar']

🔍 Analyse : Avanza_Grupo__Mataro_city_bus_.osm.pbf
   ✅ Toutes les colonnes présentes

🔍 Analyse : Avanza_Grupo__Segovia_city_bus_.osm.pbf
   ⚠️ Colonnes manquantes : ['busway', 'motorcar']

🔍 Analyse : Avanza_Grupo__Soria_city_bus_.osm.pbf
   ⚠️ Colonnes manquantes : ['busway', 'psv', 'motorcar', 'width']

🔍 Analyse : Avanza_Grupo__VAC124_HuescaLleida_with_branches_.osm.pbf

In [ ]:
import os
import gc
from pyrosm import OSM

FOLDER_PATH = r"C:\Users\hp\Documents\OSM_SP"
OUTPUT_FOLDER = os.path.join(FOLDER_PATH, "cleaned_files")
os.makedirs(OUTPUT_FOLDER, exist_ok=True)

selected_columns = [
    "id", "highway", "junction", "lanes", "maxspeed", "oneway",
    "busway", "psv", "motorcar", "access", "width", "smoothness",
    "name", "geometry", "length"
]

osm_files = [f for f in os.listdir(FOLDER_PATH) if f.endswith(".osm.pbf")]

print(f"📂 Nombre total de fichiers : {len(osm_files)}")

# 🚦 Types de routes utiles (réduction mémoire énorme)
ALLOWED_HIGHWAYS = [
    "motorway", "trunk", "primary", "secondary",
    "tertiary", "residential", "busway"
]

for i, filename in enumerate(osm_files, 1):
    print(f"\n[{i}/{len(osm_files)}] 🔹 {filename}")

    try:
        osm_path = os.path.join(FOLDER_PATH, filename)

        # ⛔ Skip fichiers trop gros (>300MB)
        if os.path.getsize(osm_path) > 300 * 1024 * 1024:
            print("   ⏭️ Fichier trop volumineux → ignoré")
            continue

        osm = OSM(osm_path)

        gdf = osm.get_network(
            network_type="driving",
            extra_attributes=selected_columns
        )

        if gdf is None or gdf.empty:
            print("   ⚠️ Aucune donnée")
            continue

        # 🚦 Filtrer routes utiles
        gdf = gdf[gdf["highway"].isin(ALLOWED_HIGHWAYS)]

        if gdf.empty:
            print("   ⚠️ Routes filtrées vides")
            continue

        # ➕ Ajouter colonnes manquantes
        for col in selected_columns:
            if col not in gdf.columns:
                gdf[col] = None

        gdf = gdf[selected_columns]

        output_path = os.path.join(
            OUTPUT_FOLDER,
            filename.replace(".osm.pbf", ".gpkg")
        )

        gdf.to_file(output_path, driver="GPKG")
        print("   ✅ Sauvegardé")

        # 🧹 Nettoyage mémoire CRUCIAL
        del gdf, osm
        gc.collect()

    except Exception as e:
        print(f"   ❌ Erreur ignorée : {e}")
        gc.collect()

📂 Nombre total de fichiers : 105

[1/105] 🔹 AISA__Bus_MadridAranda_de_DueroBurgo_de_Osma_.osm.pbf
   ✅ Sauvegardé

[2/105] 🔹 Alavabus.osm.pbf
   ✅ Sauvegardé

[3/105] 🔹 ALSA_buses.osm.pbf
   ⏭️ Fichier trop volumineux → ignoré

[4/105] 🔹 Alvarez_Travelers_Coaches.osm.pbf
   ✅ Sauvegardé

[5/105] 🔹 Ancebus.osm.pbf
   ✅ Sauvegardé

[6/105] 🔹 Area_Metropolitana_de_Barcelona__AMB_.osm.pbf
   ✅ Sauvegardé

[7/105] 🔹 AUCORSA__Autobuses_de_Cordoba_SA_.osm.pbf
   ✅ Sauvegardé

[8/105] 🔹 Auif_Irunbus__Lurraldebus_.osm.pbf
   ✅ Sauvegardé

[9/105] 🔹 AUTNA_SL.osm.pbf
   ✅ Sauvegardé

[10/105] 🔹 Autocares_Baraza__Baraza_Coaches_.osm.pbf
   ✅ Sauvegardé

[11/105] 🔹 Autocares_Rias_Baixas__Rias_Baixas_Coaches_.osm.pbf
   ✅ Sauvegardé

[12/105] 🔹 Autocorb_Coaches.osm.pbf
   ✅ Sauvegardé

[13/105] 🔹 Autoridad_de_Transporte_Metropolitano_del_Area_de_Barcelona__ATM__Buses_and_trains_in_Catalonia__full_version_.osm.pbf
   ⏭️ Fichier trop volumineux → ignoré

[14/105] 🔹 Avanza_Grupo__Avila_city_bus_.osm.pbf
   ✅ Sauvegardé

[15/105] 🔹 Avanza_Grupo__Huesca_city_bus_.osm.pbf
   ✅ Sauvegardé

[16/105] 🔹 Avanza_Grupo__Mataro_city_bus_.osm.pbf
   ✅ Sauvegardé

[17/105] 🔹 Avanza_Grupo__Segovia_city_bus_.osm.pbf
   ✅ Sauvegardé

[18/105] 🔹 Avanza_Grupo__Soria_city_bus_.osm.pbf
   ✅ Sauvegardé

[19/105] 🔹 Avanza_Grupo__VAC124_HuescaLleida_with_branches_.osm.pbf
   ✅ Sauvegardé

[20/105] 🔹 Avanza_Grupo__VAC245_HuescaBarcelona_.osm.pbf
   ✅ Sauvegardé

[21/105] 🔹 Bermibusa.osm.pbf
   ✅ Sauvegardé

[22/105] 🔹 Bizkaibus.osm.pbf
   ✅ Sauvegardé

[23/105] 🔹 BlaBlaCar_Bus.osm.pbf
   ⏭️ Fichier trop volumineux → ignoré

[24/105] 🔹 Catalonia_Area_de_Barcelona.osm.pbf
   ⏭️ Fichier trop volumineux → ignoré

[25/105] 🔹 City_Council_of_Las_Palmas_de_Gran_Canaria__city_bus_.osm.pbf
   ⚠️ Aucune donnée

[26/105] 🔹 Collegamenti_marittimi_Grandi_Navi_Veloci.osm.pbf
   ⏭️ Fichier trop volumineux → ignoré

[27/105] 🔹 Collegamenti_marittimi_Grimaldi.osm.pbf
   ⏭️ Fichier trop volumineux → ignoré

[28/105] 🔹 Consorcio_Regional_de_Transportes_de_Madrid_CRTM_Intercity_Buses__Madrid_Intercity_Bus_.osm.pbf

C:\Users\hp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pyrosm\pyrosm.py:249: UserWarning: Could not find any edges for given area.
  edges, node_gdf = get_network_data(

   ✅ Sauvegardé

[29/105] 🔹 Consorcio_Regional_de_Transportes_de_Madrid_CRTM_Light_Rail_Network__Red_de_Metro_Ligero_.osm.pbf
   ✅ Sauvegardé

[30/105] 🔹 Consorcio_Regional_de_Transportes_de_Madrid_CRTM_Madrid_City_Bus__Autobus_urbano_de_Madrid_.osm.pbf
   ✅ Sauvegardé

[31/105] 🔹 Consorcio_Regional_de_Transportes_de_Madrid_Metro_Ligero_de_Madrid.osm.pbf
   ✅ Sauvegardé

[32/105] 🔹 Consorcio_Regional_de_Transportes_de_Madrid_Reseau_de_navettes_CRTM__Red_de_Cercanias_.osm.pbf
   ✅ Sauvegardé

[33/105] 🔹 Costa_Coaches.osm.pbf
   ✅ Sauvegardé

[34/105] 🔹 Cots_Alsina.osm.pbf
   ✅ Sauvegardé

[35/105] 🔹 dBus__Donostiabus_.osm.pbf
   ✅ Sauvegardé

[36/105] 🔹 Direxis_Masats.osm.pbf
   ✅ Sauvegardé

[37/105] 🔹 Direxis_TGO__Transportes_Generales_de_Olesa_.osm.pbf
   ✅ Sauvegardé

[38/105] 🔹 El_Transbordador_de_Vizcaya.osm.pbf
   ⚠️ Routes filtrées vides

[39/105] 🔹 El_Transbordador_de_Vizcaya__Bizkaia_Bridge_Ferry_.osm.pbf
   ⚠️ Routes filtrées vides

[40/105] 🔹 Empresa_Municipal_de_Transportes_de_Madrid__EMT_Madrid_.osm.pbf
   ✅ Sauvegardé

[41/105] 🔹 Empresa_Municipal_de_Transportes_de_Valencia__EMT_Valencia_.osm.pbf
   ✅ Sauvegardé

[42/105] 🔹 Empresa_Municipal_de_Transports_Urbans_de_Palma_de_Mallorca.osm.pbf
   ✅ Sauvegardé

[43/105] 🔹 EMT_Tarragona.osm.pbf
   ✅ Sauvegardé

[44/105] 🔹 Erandio_City_Council__Erandio_Busa_.osm.pbf
   ✅ Sauvegardé

[45/105] 🔹 Etxebarri_Town_Hall.osm.pbf
   ✅ Sauvegardé

[46/105] 🔹 Euskotren.osm.pbf
   ✅ Sauvegardé

[47/105] 🔹 Ferry_Fred_Olsen__Fred_Olsen_Express_.osm.pbf

C:\Users\hp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pyrosm\pyrosm.py:249: UserWarning: Could not find any edges for given area.
  edges, node_gdf = get_network_data(

   ⚠️ Aucune donnée

[48/105] 🔹 FGV__Generalitat_Valenciana_Metro_de_Valencia.osm.pbf
   ✅ Sauvegardé

[49/105] 🔹 FGV__Generalitat_Valenciana_Trains_and_trams_in_Alicante_and_the_Costa_Blanca.osm.pbf
   ✅ Sauvegardé

[50/105] 🔹 Funiculaire_de_Artxanda.osm.pbf
   ✅ Sauvegardé

[51/105] 🔹 Generalitat_of_Catalonia__Intercity_bus_.osm.pbf
   ⏭️ Fichier trop volumineux → ignoré

[52/105] 🔹 Gobierno_de_Cantabria__Bus_en_Cantabrie_.osm.pbf
   ⏭️ Fichier trop volumineux → ignoré

[53/105] 🔹 Granada_City_Council__Granada_city_bus_.osm.pbf
   ✅ Sauvegardé

[54/105] 🔹 Guaguas_Municipales.osm.pbf
   ⚠️ Aucune donnée

[55/105] 🔹 Junta_de_Extremadura__Bus_du_gouvernement_regional_dEstremadure_.osm.pbf

C:\Users\hp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pyrosm\pyrosm.py:249: UserWarning: Could not find any edges for given area.
  edges, node_gdf = get_network_data(

   ✅ Sauvegardé

[56/105] 🔹 Kbus__Barakaldo_urban_.osm.pbf
   ✅ Sauvegardé

[57/105] 🔹 Lazara_Coaches.osm.pbf
   ✅ Sauvegardé

[58/105] 🔹 La_Burundesa_SA.osm.pbf

In [ ]:
import os
import geopandas as gpd
import gc

# 🗂️ Chemins
FOLDER_PATH = r"C:\Users\hp\Documents\OSM_SP\cleaned_files"  # dossier contenant les GPKG filtrés
OUTPUT_FILE = r"C:\Users\hp\Documents\OSM_SP\OSM_Spain_Fused.gpkg"

# Créer le dossier de sortie si non existant
os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)

# ✅ Colonnes à conserver
selected_columns = [
    "id", "highway", "junction", "lanes", "maxspeed", "oneway",
    "busway", "psv", "motorcar", "access", "width",
    "smoothness", "name", "geometry", "length"
]

# Lister tous les fichiers GPKG
gpkg_files = [f for f in os.listdir(FOLDER_PATH) if f.endswith(".gpkg")]
print(f"📂 Nombre de fichiers à fusionner : {len(gpkg_files)}")

# Liste pour stocker les GeoDataFrames
gdf_list = []

for i, file_name in enumerate(gpkg_files, start=1):
    file_path = os.path.join(FOLDER_PATH, file_name)
    print(f"[{i}/{len(gpkg_files)}] 🔹 Lecture : {file_name}")
    
    try:
        gdf = gpd.read_file(file_path)
        
        # garder uniquement les colonnes sélectionnées si elles existent
        cols_to_keep = [c for c in selected_columns if c in gdf.columns]
        gdf = gdf[cols_to_keep]
        
        gdf_list.append(gdf)
        
        # Libérer la mémoire
        del gdf
        gc.collect()
        
    except Exception as e:
        print(f"❌ Erreur lecture {file_name} : {e}")

# Fusionner tous les GeoDataFrames
print("\n🔗 Fusion des fichiers...")
try:
    fused_gdf = gpd.GeoDataFrame(pd.concat(gdf_list, ignore_index=True), crs=gdf_list[0].crs)
    print(f"✅ Fusion terminée, total lignes : {len(fused_gdf)}")
    
    # Sauvegarder en GPKG
    fused_gdf.to_file(OUTPUT_FILE, driver="GPKG")
    print(f"💾 Fichier fusionné sauvegardé : {OUTPUT_FILE}")
    
    # Libérer la mémoire
    del fused_gdf, gdf_list
    gc.collect()

except Exception as e:
    print(f"❌ Erreur lors de la fusion : {e}")

🔹 Traitement : Generalitat_of_Catalonia__Intercity_bus_.osm.pbf
❌ Erreur mémoire → fichier ignoré

🔹 Traitement : Gobierno_de_Cantabria__Bus_en_Cantabrie_.osm.pbf
❌ Erreur mémoire → fichier ignoré

🔹 Traitement : ALSA_buses.osm.pbf
❌ Erreur mémoire → fichier ignoré